# State-only model move from core → invoices app.
#
# Tables (core_invoice, core_invoicesettings, core_servicecategory,
# core_serviceitem, core_invoice_donations) stay put on disk via Meta.db_table.
# These migrations only update Django's ORM state graph; no DDL runs.
#
# Companion: notifications/0001 contained a RunPython for ContentType
# repointing — for invoices we add the equivalent to the initial migration.

# Generated by Django 5.2.13 on 2026-04-19 00:05

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def _repoint_contenttype_forward(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model in ("invoice", "invoicesettings", "servicecategory", "serviceitem"):
        ContentType.objects.filter(app_label="core", model=model).update(
            app_label="invoices"
        )


def _repoint_contenttype_reverse(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model in ("invoice", "invoicesettings", "servicecategory", "serviceitem"):
        ContentType.objects.filter(app_label="invoices", model=model).update(
            app_label="core"
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0064_remove_invoice_fks_state_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ServiceCategory',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('name', models.CharField(help_text='Service category name (e.g., Set Ups, Letter Set Up)', max_length=255, unique=True)),
                        ('description', models.TextField(blank=True, help_text='Optional description of the service category')),
                        ('is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
                        ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name': 'Service Category',
                        'verbose_name_plural': 'Service Categories',
                        'db_table': 'core_servicecategory',
                        'ordering': ['order', 'name'],
                    },
                ),
                migrations.CreateModel(
                    name='InvoiceSettings',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('price_per_donation', models.DecimalField(decimal_places=4, default=0.05, help_text='Price per donation captured (£)', max_digits=8)),
                        ('price_per_gift_aid', models.DecimalField(decimal_places=4, default=0.1, help_text='Price per gift aid declaration (£)', max_digits=8)),
                        ('price_per_letter', models.DecimalField(decimal_places=4, default=0.25, help_text='Price per letter generated (£)', max_digits=8)),
                        ('price_per_campaign', models.DecimalField(decimal_places=4, default=5.0, help_text='Price per campaign created (£)', max_digits=8)),
                        ('price_per_hgv', models.DecimalField(decimal_places=4, default=0.5, help_text='Price per HGV identified (£)', max_digits=8)),
                        ('price_per_lgv', models.DecimalField(decimal_places=4, default=0.1, help_text='Price per LGV identified (£)', max_digits=8)),
                        ('price_per_donor_response', models.DecimalField(decimal_places=4, default=0.15, help_text='Price per donor response received (£)', max_digits=8)),
                        ('price_per_letter_batch', models.DecimalField(decimal_places=4, default=2.0, help_text='Price per letter batch created (£)', max_digits=8)),
                        ('price_per_campaign_field', models.DecimalField(decimal_places=4, default=0.5, help_text='Price per campaign field configured (£)', max_digits=8)),
                        ('price_per_donor_upload', models.DecimalField(decimal_places=4, default=1.5, help_text='Price per donor CSV upload (£)', max_digits=8)),
                        ('price_per_segment', models.DecimalField(decimal_places=4, default=3.0, help_text='Price per donor segment created (£)', max_digits=8)),
                        ('price_per_email', models.DecimalField(decimal_places=4, default=0.08, help_text='Price per email notification (£)', max_digits=8)),
                        ('price_per_sms', models.DecimalField(decimal_places=4, default=0.2, help_text='Price per SMS notification (£)', max_digits=8)),
                        ('price_per_pdf_export', models.DecimalField(decimal_places=4, default=0.3, help_text='Price per PDF export (£)', max_digits=8)),
                        ('price_per_csv_export', models.DecimalField(decimal_places=4, default=0.2, help_text='Price per CSV export (£)', max_digits=8)),
                        ('price_per_excel_export', models.DecimalField(decimal_places=4, default=0.25, help_text='Price per Excel export (£)', max_digits=8)),
                        ('price_per_export', models.DecimalField(decimal_places=4, default=0.15, help_text='Price per export operation (£)', max_digits=8)),
                        ('price_per_approval', models.DecimalField(decimal_places=4, default=1.0, help_text='Price per approval workflow (£)', max_digits=8)),
                        ('price_per_audit_log', models.DecimalField(decimal_places=4, default=0.05, help_text='Price per audit log entry (£)', max_digits=8)),
                        ('price_per_portal_session', models.DecimalField(decimal_places=4, default=0.1, help_text='Price per portal session (£)', max_digits=8)),
                        ('price_per_package_code', models.DecimalField(decimal_places=4, default=0.3, help_text='Price per package code (£)', max_digits=8)),
                        ('price_per_address_lookup', models.DecimalField(decimal_places=4, default=0.02, help_text='Price per address lookup (£)', max_digits=8)),
                        ('price_per_data_file_upload', models.DecimalField(decimal_places=4, default=2.5, help_text='Price per data file upload (£)', max_digits=8)),
                        ('price_per_db_query', models.DecimalField(decimal_places=4, default=0.001, help_text='Price per database query (£)', max_digits=8)),
                        ('price_per_notification', models.DecimalField(decimal_places=4, default=0.02, help_text='Price per notification sent (£)', max_digits=8)),
                        ('price_per_data_file', models.DecimalField(decimal_places=4, default=2.0, help_text='Price per data file processed (£)', max_digits=8)),
                        ('price_per_batch', models.DecimalField(decimal_places=4, default=0.5, help_text='Price per batch operation (£)', max_digits=8)),
                        ('price_per_report', models.DecimalField(decimal_places=4, default=1.0, help_text='Price per report generated (£)', max_digits=8)),
                        ('price_per_template', models.DecimalField(decimal_places=4, default=2.5, help_text='Price per template created (£)', max_digits=8)),
                        ('price_per_user', models.DecimalField(decimal_places=4, default=5.0, help_text='Price per user managed (£)', max_digits=8)),
                        ('price_per_donor_added', models.DecimalField(decimal_places=4, default=0.05, help_text='Price per donor added (£)', max_digits=8)),
                        ('price_per_donor_updated', models.DecimalField(decimal_places=4, default=0.02, help_text='Price per donor updated (£)', max_digits=8)),
                        ('price_per_api_call', models.DecimalField(decimal_places=4, default=0.001, help_text='Price per API call (£)', max_digits=8)),
                        ('price_per_mb_storage', models.DecimalField(decimal_places=4, default=0.01, help_text='Price per MB storage used (£)', max_digits=8)),
                        ('default_tax_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='Default VAT/tax rate percentage', max_digits=5)),
                        ('default_due_days', models.PositiveIntegerField(default=30, help_text='Default payment due days from issue date')),
                        ('company_name', models.CharField(default='INSYTE', help_text='Company name for invoices', max_length=255)),
                        ('company_address', models.TextField(blank=True, default='', help_text='Company address for invoices')),
                        ('company_phone', models.CharField(blank=True, default='', help_text='Company phone number', max_length=50)),
                        ('company_email', models.EmailField(blank=True, default='', help_text='Company email address', max_length=254)),
                        ('company_vat_number', models.CharField(blank=True, default='', help_text='Company VAT registration number', max_length=50)),
                        ('company_logo_url', models.URLField(blank=True, default='', help_text='URL to company logo for invoices')),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_settings_updates', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Invoice Settings',
                        'verbose_name_plural': 'Invoice Settings',
                        'db_table': 'core_invoicesettings',
                    },
                ),
                migrations.CreateModel(
                    name='Invoice',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                        ('billing_period_start', models.DateField()),
                        ('billing_period_end', models.DateField()),
                        ('issue_date', models.DateField(auto_now_add=True)),
                        ('due_date', models.DateField()),
                        ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                        ('total_donations_captured', models.PositiveIntegerField(default=0, help_text='Total donations recorded')),
                        ('total_donation_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total donation amount (£)', max_digits=12)),
                        ('gift_aid_captured', models.PositiveIntegerField(default=0, help_text='Gift aid declarations')),
                        ('gift_aid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Gift aid amount (£)', max_digits=12)),
                        ('campaigns_created', models.PositiveIntegerField(default=0, help_text='New campaigns created')),
                        ('campaigns_updated', models.PositiveIntegerField(default=0, help_text='Campaign updates')),
                        ('campaign_fields_configured', models.PositiveIntegerField(default=0, help_text='Campaign fields configured')),
                        ('letters_generated', models.PositiveIntegerField(default=0, help_text='Thank you letters generated')),
                        ('letter_batches_created', models.PositiveIntegerField(default=0, help_text='Letter batch operations')),
                        ('letter_templates_used', models.PositiveIntegerField(default=0, help_text='Letter templates utilized')),
                        ('donors_added', models.PositiveIntegerField(default=0, help_text='New donors added')),
                        ('donors_updated', models.PositiveIntegerField(default=0, help_text='Donor records updated')),
                        ('donor_uploads_processed', models.PositiveIntegerField(default=0, help_text='Donor CSV uploads')),
                        ('donor_responses_received', models.PositiveIntegerField(default=0, help_text='Donor responses tracked')),
                        ('hgv_identified', models.PositiveIntegerField(default=0, help_text='High Gift Value donors')),
                        ('lgv_identified', models.PositiveIntegerField(default=0, help_text='Low Gift Value donors')),
                        ('data_files_processed', models.PositiveIntegerField(default=0, help_text='Data files imported')),
                        ('data_file_uploads', models.PositiveIntegerField(default=0, help_text='File upload operations')),
                        ('batch_operations_completed', models.PositiveIntegerField(default=0, help_text='Batch processing jobs')),
                        ('segments_created', models.PositiveIntegerField(default=0, help_text='Donor segments created')),
                        ('email_notifications_sent', models.PositiveIntegerField(default=0, help_text='Email notifications')),
                        ('sms_notifications_sent', models.PositiveIntegerField(default=0, help_text='SMS notifications')),
                        ('donor_notifications_sent', models.PositiveIntegerField(default=0, help_text='General notifications')),
                        ('reports_generated', models.PositiveIntegerField(default=0, help_text='Reports generated')),
                        ('pdf_exports', models.PositiveIntegerField(default=0, help_text='PDF exports')),
                        ('csv_exports', models.PositiveIntegerField(default=0, help_text='CSV exports')),
                        ('excel_exports', models.PositiveIntegerField(default=0, help_text='Excel exports')),
                        ('export_operations', models.PositiveIntegerField(default=0, help_text='Total export operations')),
                        ('approval_workflows_processed', models.PositiveIntegerField(default=0, help_text='Approval workflows')),
                        ('audit_logs_generated', models.PositiveIntegerField(default=0, help_text='Audit trail entries')),
                        ('templates_created', models.PositiveIntegerField(default=0, help_text='Templates configured')),
                        ('users_managed', models.PositiveIntegerField(default=0, help_text='User accounts managed')),
                        ('client_portal_sessions', models.PositiveIntegerField(default=0, help_text='Client portal logins')),
                        ('package_codes_used', models.PositiveIntegerField(default=0, help_text='Package codes utilized')),
                        ('api_calls_made', models.PositiveIntegerField(default=0, help_text='API calls executed')),
                        ('address_lookups', models.PositiveIntegerField(default=0, help_text='Address validation lookups')),
                        ('storage_used_mb', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Storage used (MB)', max_digits=10)),
                        ('database_queries', models.PositiveIntegerField(default=0, help_text='Database queries executed')),
                        ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                        ('processing_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                        ('setup_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                        ('additional_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                        ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                        ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                        ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                        ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                        ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                        ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                        ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                        ('payment_method', models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cheque', 'Cheque'), ('cash', 'Cash'), ('other', 'Other')], max_length=50)),
                        ('payment_reference', models.CharField(blank=True, max_length=255)),
                        ('payment_date', models.DateField(blank=True, null=True)),
                        ('notes', models.TextField(blank=True)),
                        ('terms_and_conditions', models.TextField(blank=True, default='Payment is due within 30 days of invoice date. Late payments may incur additional charges.')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('campaign', models.ForeignKey(blank=True, help_text='Optional: Generate invoice for specific campaign only', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.campaign')),
                        ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.client')),
                        ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                        ('donations', models.ManyToManyField(blank=True, help_text='Specific donations included in this invoice for detailed line items', related_name='invoices', to='core.donation')),
                    ],
                    options={
                        'verbose_name': 'Invoice',
                        'verbose_name_plural': 'Invoices',
                        'db_table': 'core_invoice',
                        'ordering': ['-issue_date', '-invoice_number'],
                        'indexes': [models.Index(fields=['client', '-issue_date'], name='core_invoic_client__25b4ff_idx'), models.Index(fields=['status', '-issue_date'], name='core_invoic_status_c774a4_idx')],
                    },
                ),
                migrations.CreateModel(
                    name='ServiceItem',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('description', models.CharField(help_text='Service description (e.g., Payment Gateway integration)', max_length=500)),
                        ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price in GBP (£)', max_digits=10)),
                        ('pricing_unit', models.CharField(help_text='Pricing comment (e.g., each, per hour, per month, per GB per month)', max_length=100)),
                        ('is_active', models.BooleanField(default=True, help_text='Whether this service is active')),
                        ('is_default', models.BooleanField(default=False, help_text='Whether this should appear in invoice by default')),
                        ('order', models.PositiveIntegerField(default=0, help_text='Display order within category')),
                        ('notes', models.TextField(blank=True, help_text='Additional notes or details (e.g., ie: SagePay, Barclay Card, WorldPay)')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='invoices.servicecategory')),
                    ],
                    options={
                        'verbose_name': 'Service Item',
                        'verbose_name_plural': 'Service Items',
                        'db_table': 'core_serviceitem',
                        'ordering': ['category', 'order', 'description'],
                        'constraints': [models.UniqueConstraint(fields=('category', 'description'), name='unique_service_item_category_description')],
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(
            _repoint_contenttype_forward,
            _repoint_contenttype_reverse,
        ),
    ]
