# Generated by Django 5.2.13 on 2026-04-19 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial_state_only'),
        ('invoices', '0001_initial_state_only'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='invoice',
                    name='client',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client'),
                ),
            ],
            database_operations=[],
        ),
    ]
