# Generated by Django 5.2.13 on 2026-04-19 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_add_campaign_models_state_only'),
        ('invoices', '0002_remove_client_state_only'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='invoice',
                    name='campaign',
                    field=models.ForeignKey(blank=True, help_text='Optional: Generate invoice for specific campaign only', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='campaigns.campaign'),
                ),
            ],
            database_operations=[],
        ),
    ]
