# Generated by Django 5.2.13 on 2026-05-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoice_donations'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoices_in_client__fce897_idx',
            old_name='core_invoic_client__25b4ff_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoices_in_status_fbe820_idx',
            old_name='core_invoic_status_c774a4_idx',
        ),
        migrations.AlterModelTable(
            name='invoice',
            table=None,
        ),
        migrations.AlterModelTable(
            name='invoicesettings',
            table=None,
        ),
        migrations.AlterModelTable(
            name='servicecategory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='serviceitem',
            table=None,
        ),
    ]
