# Generated by Django 5.2.8 on 2025-12-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='donations',
            field=models.ManyToManyField(blank=True, help_text='Specific donations included in this invoice for detailed line items', related_name='invoices', to='core.donation'),
        ),
    ]
