# Generated by Django 5.2.8 on 2025-12-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_invoice_donations_m2m'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['campaign', 'created_at'], name='donation_camp_created_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['campaign', 'donation_date'], name='donation_camp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['payment_method'], name='donation_payment_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor'], name='donation_donor_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['data_file_donor'], name='donation_datadonor_idx'),
        ),
    ]
