# Generated by Django 5.2.9 on 2025-12-24 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_donation_performance_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='close_date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='open_date',
        ),
    ]
