# Generated by Django 5.2.9 on 2025-12-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_campaign_close_date_remove_campaign_open_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='appeal_reference',
        ),
    ]
