# Generated by Django 5.2.9 on 2026-01-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_campaign_appeal_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='qa_notes',
            field=models.TextField(blank=True, default='', help_text='Reviewer notes for donation-level QA actions'),
        ),
        migrations.AddField(
            model_name='donation',
            name='qa_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], db_index=True, default='pending', help_text='QA review status for this donation', max_length=20),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['qa_status'], name='donation_qa_status_idx'),
        ),
    ]
