# Generated by Django 5.2.9 on 2026-01-14 14:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_donation_qa_notes_donation_qa_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', help_text='Online payment processing status', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='unpaid', help_text='Payment processing status', max_length=20),
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_customer_id', models.CharField(db_index=True, help_text='Stripe customer ID (starts with cus_)', max_length=255, unique=True)),
                ('email', models.EmailField(help_text='Customer email address', max_length=254)),
                ('name', models.CharField(help_text='Customer full name', max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional Stripe customer metadata')),
                ('client', models.ForeignKey(blank=True, help_text='Linked charity/client organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_customers', to='core.client')),
                ('donor', models.ForeignKey(blank=True, help_text='Linked donor for donation payments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_customers', to='core.donor')),
            ],
            options={
                'verbose_name': 'Stripe Customer',
                'verbose_name_plural': 'Stripe Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripePaymentMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_payment_method_id', models.CharField(db_index=True, help_text='Stripe payment method ID (starts with pm_)', max_length=255, unique=True)),
                ('type', models.CharField(default='card', help_text='Payment method type (card, etc.)', max_length=50)),
                ('card_brand', models.CharField(blank=True, help_text='Card brand (visa, mastercard, etc.)', max_length=50, null=True)),
                ('card_last4', models.CharField(blank=True, help_text='Last 4 digits of card', max_length=4, null=True)),
                ('card_exp_month', models.IntegerField(blank=True, help_text='Card expiration month', null=True)),
                ('card_exp_year', models.IntegerField(blank=True, help_text='Card expiration year', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default payment method for customer')),
                ('stripe_customer', models.ForeignKey(help_text='Associated Stripe customer', on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='core.stripecustomer')),
            ],
            options={
                'verbose_name': 'Stripe Payment Method',
                'verbose_name_plural': 'Stripe Payment Methods',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_payment_intent_id', models.CharField(db_index=True, help_text='Stripe payment intent ID (starts with pi_)', max_length=255, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, db_index=True, help_text='Stripe charge ID (starts with ch_)', max_length=255, null=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, db_index=True, help_text='Stripe checkout session ID (starts with cs_)', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12)),
                ('currency', models.CharField(default='GBP', help_text='Payment currency (GBP, USD, EUR)', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Payment status', max_length=30)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=0, help_text='Total amount refunded', max_digits=12)),
                ('refund_reason', models.TextField(blank=True, help_text='Reason for refund', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum retry attempts')),
                ('next_retry_at', models.DateTimeField(blank=True, help_text='Scheduled next retry time', null=True)),
                ('last_retry_at', models.DateTimeField(blank=True, help_text='Last retry attempt time', null=True)),
                ('stripe_response', models.JSONField(blank=True, default=dict, help_text='Full Stripe API response')),
                ('error_message', models.TextField(blank=True, help_text='Error message if payment failed', null=True)),
                ('error_code', models.CharField(blank=True, db_index=True, help_text='Stripe error code', max_length=100, null=True)),
                ('error_type', models.CharField(blank=True, help_text='Stripe error type', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Payment description', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment metadata')),
                ('donation', models.ForeignKey(blank=True, help_text='Donation payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_payments', to='core.donation')),
                ('invoice', models.ForeignKey(blank=True, help_text='Invoice being paid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_payments', to='core.invoice')),
                ('processed_by', models.ForeignKey(blank=True, help_text='User who initiated payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL)),
                ('stripe_customer', models.ForeignKey(help_text='Customer who made the payment', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.stripecustomer')),
                ('stripe_payment_method', models.ForeignKey(blank=True, help_text='Payment method used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.stripepaymentmethod')),
            ],
            options={
                'verbose_name': 'Stripe Payment',
                'verbose_name_plural': 'Stripe Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_event_id', models.CharField(db_index=True, help_text='Stripe event ID (starts with evt_)', max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, help_text='Stripe event type (e.g., payment_intent.succeeded)', max_length=100)),
                ('payload', models.JSONField(help_text='Full webhook event payload')),
                ('processed', models.BooleanField(db_index=True, default=False, help_text='Whether event has been processed')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When event was processed', null=True)),
                ('processing_attempts', models.IntegerField(default=0, help_text='Number of processing attempts')),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('payment', models.ForeignKey(blank=True, help_text='Related payment record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='core.stripepayment')),
            ],
            options={
                'verbose_name': 'Stripe Webhook Event',
                'verbose_name_plural': 'Stripe Webhook Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stripecustomer',
            index=models.Index(fields=['stripe_customer_id'], name='core_stripe_stripe__47d8b9_idx'),
        ),
        migrations.AddIndex(
            model_name='stripecustomer',
            index=models.Index(fields=['email'], name='core_stripe_email_bc22fc_idx'),
        ),
        migrations.AddIndex(
            model_name='stripepaymentmethod',
            index=models.Index(fields=['stripe_payment_method_id'], name='core_stripe_stripe__87eb20_idx'),
        ),
        migrations.AddIndex(
            model_name='stripepaymentmethod',
            index=models.Index(fields=['stripe_customer', 'is_default'], name='core_stripe_stripe__6d6831_idx'),
        ),
        migrations.AddIndex(
            model_name='stripepayment',
            index=models.Index(fields=['stripe_payment_intent_id'], name='core_stripe_stripe__613551_idx'),
        ),
        migrations.AddIndex(
            model_name='stripepayment',
            index=models.Index(fields=['stripe_charge_id'], name='core_stripe_stripe__08c50b_idx'),
        ),
        migrations.AddIndex(
            model_name='stripepayment',
            index=models.Index(fields=['stripe_checkout_session_id'], name='core_stripe_stripe__7d4455_idx'),
        ),
        migrations.AddIndex(
            model_name='stripepayment',
            index=models.Index(fields=['status', '-created_at'], name='core_stripe_status_b73c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='stripepayment',
            index=models.Index(fields=['invoice', 'status'], name='core_stripe_invoice_604341_idx'),
        ),
        migrations.AddIndex(
            model_name='stripepayment',
            index=models.Index(fields=['donation', 'status'], name='core_stripe_donatio_ab0c16_idx'),
        ),
        migrations.AddIndex(
            model_name='stripepayment',
            index=models.Index(fields=['next_retry_at'], name='core_stripe_next_re_0ea01b_idx'),
        ),
        migrations.AddIndex(
            model_name='stripewebhookevent',
            index=models.Index(fields=['stripe_event_id'], name='core_stripe_stripe__412803_idx'),
        ),
        migrations.AddIndex(
            model_name='stripewebhookevent',
            index=models.Index(fields=['event_type', '-created_at'], name='core_stripe_event_t_9ba688_idx'),
        ),
        migrations.AddIndex(
            model_name='stripewebhookevent',
            index=models.Index(fields=['processed', '-created_at'], name='core_stripe_process_f89d36_idx'),
        ),
    ]
