# Generated by Django 5.2.9 on 2026-01-14 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_donation_payment_status_invoice_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='campaign',
            name='failed_payments',
            field=models.IntegerField(default=0, help_text='Count of failed payments'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='payment_eligible',
            field=models.BooleanField(db_index=True, default=False, help_text='Campaign is eligible for payment processing (all batches QA approved)'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='payment_processed_at',
            field=models.DateTimeField(blank=True, help_text='When payment processing was completed', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='payment_processed_by',
            field=models.ForeignKey(blank=True, help_text='User who processed campaign payments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='payment_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('partially_completed', 'Partially Completed'), ('failed', 'Failed')], db_index=True, default='not_started', help_text='Overall payment status for campaign', max_length=30),
        ),
        migrations.AddField(
            model_name='campaign',
            name='successful_payments',
            field=models.IntegerField(default=0, help_text='Count of successful payments'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount of credit card payments in campaign', max_digits=12),
        ),
        migrations.AddField(
            model_name='donationbatch',
            name='failed_payment_count',
            field=models.IntegerField(default=0, help_text='Count of failed credit card payments'),
        ),
        migrations.AddField(
            model_name='donationbatch',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, help_text='When payment processing completed', null=True),
        ),
        migrations.AddField(
            model_name='donationbatch',
            name='payment_initiated_at',
            field=models.DateTimeField(blank=True, help_text='When payment processing started', null=True),
        ),
        migrations.AddField(
            model_name='donationbatch',
            name='payment_initiated_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated payment processing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_payments_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationbatch',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partially_completed', 'Partially Completed')], db_index=True, default='pending', help_text='Payment processing status for this batch', max_length=30),
        ),
        migrations.AddField(
            model_name='donationbatch',
            name='successful_payment_count',
            field=models.IntegerField(default=0, help_text='Count of successful credit card payments'),
        ),
    ]
