# Generated by Django 5.2.9 on 2026-01-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_invoice_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_manager_email',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_manager_emails',
            field=models.TextField(blank=True, help_text='Comma-separated list of email addresses to notify for HGV donations', null=True),
        ),
    ]
