# Generated by Django 5.2.9 on 2026-01-29 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_donation_payment_methods'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayingInSlip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slip_number', models.CharField(db_index=True, help_text='Unique slip number for bank statement reconciliation', max_length=50, unique=True)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('postal_order', 'Postal Order'), ('caf', 'CAF Voucher'), ('other_charity_voucher', 'Other Charity Voucher'), ('mixed', 'Mixed')], default='mixed', help_text='Type of payments in this slip', max_length=30)),
                ('banking_date', models.DateField(db_index=True, help_text='Date the payments are being banked')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount in the slip', max_digits=12)),
                ('total_items', models.PositiveIntegerField(default=0, help_text='Number of donations in the slip')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Banking'), ('banked', 'Banked')], db_index=True, default='draft', help_text='Slip status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the slip')),
                ('banked_at', models.DateTimeField(blank=True, help_text='When slip was marked as banked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banked_by', models.ForeignKey(blank=True, help_text='User who marked the slip as banked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banked_slips', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(help_text='Client this slip belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='paying_in_slips', to='core.client')),
                ('created_by', models.ForeignKey(help_text='User who created the slip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_paying_in_slips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paying-In Slip',
                'verbose_name_plural': 'Paying-In Slips',
                'ordering': ['-banking_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='paying_in_slip',
            field=models.ForeignKey(blank=True, help_text='Paying-in slip for bank statement reconciliation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='core.payinginslip'),
        ),
        migrations.AddIndex(
            model_name='payinginslip',
            index=models.Index(fields=['client', 'banking_date'], name='core_paying_client__638e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='payinginslip',
            index=models.Index(fields=['status', 'banking_date'], name='core_paying_status_2f8864_idx'),
        ),
    ]
