# Generated by Django 5.2.9 on 2026-02-11 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_payinginslip_donation_paying_in_slip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanUploadProgress',
            fields=[
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='scan_progress', serialize=False, to='core.campaign')),
                ('total_uploaded', models.PositiveIntegerField(default=0)),
                ('total_expected', models.PositiveIntegerField(default=0, help_text='Expected number of scans (0 = unknown).')),
                ('latest_urn', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('scanning', 'Scanning'), ('complete', 'Complete'), ('error', 'Error')], default='idle', max_length=20)),
                ('last_upload_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scan Upload Progress',
                'verbose_name_plural': 'Scan Upload Progress',
            },
        ),
    ]
