# Generated by Django 5.2.9 on 2026-02-11 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_scan_upload_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Update STATUS_CHOICES to include new statuses
        migrations.AlterField(
            model_name='payinginslip',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Draft'),
                    ('ready', 'Ready for Banking'),
                    ('submitted_to_bank', 'Submitted to Bank'),
                    ('processed', 'Processed'),
                    ('partially_processed', 'Partially Processed'),
                    ('failed', 'Failed'),
                    ('banked', 'Banked'),
                ],
                db_index=True,
                default='draft',
                help_text='Slip status',
                max_length=20,
            ),
        ),
        # Add bank_processed_date field
        migrations.AddField(
            model_name='payinginslip',
            name='bank_processed_date',
            field=models.DateField(
                blank=True,
                help_text='Actual date when bank processed the slip',
                null=True,
            ),
        ),
        # Add processed_amount field
        migrations.AddField(
            model_name='payinginslip',
            name='processed_amount',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Amount successfully processed by bank',
                max_digits=12,
                null=True,
            ),
        ),
        # Add completion_status field
        migrations.AddField(
            model_name='payinginslip',
            name='completion_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('full_success', 'Fully Processed'),
                    ('partial_success', 'Partially Processed'),
                    ('issues', 'Processed with Issues'),
                    ('failed', 'Failed to Process'),
                ],
                help_text='Processing outcome status',
                max_length=20,
                null=True,
            ),
        ),
        # Add processing_issues field
        migrations.AddField(
            model_name='payinginslip',
            name='processing_issues',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Array of processing issue codes',
            ),
        ),
        # Add custom_issue field
        migrations.AddField(
            model_name='payinginslip',
            name='custom_issue',
            field=models.TextField(
                blank=True,
                help_text='User-entered description of processing issues',
            ),
        ),
        # Add processed_by field
        migrations.AddField(
            model_name='payinginslip',
            name='processed_by',
            field=models.ForeignKey(
                blank=True,
                help_text='User who recorded bank processing results',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='processed_slips',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Add processed_at field
        migrations.AddField(
            model_name='payinginslip',
            name='processed_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When processing information was recorded',
                null=True,
            ),
        ),
    ]
