# Generated by Django 5.2.9 on 2026-02-13 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_enhance_paying_in_slip_processing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payinginslip',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Primary client (nullable for multi-client slips)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paying_in_slips', to='core.client'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['paying_in_slip', 'qa_status', 'payment_method'], name='donation_banking_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['batch', 'paying_in_slip'], name='donation_batch_slip_idx'),
        ),
        migrations.AddIndex(
            model_name='donationbatch',
            index=models.Index(fields=['campaign', 'status'], name='batch_campaign_status_idx'),
        ),
    ]
