# Generated by Django 5.2.9 on 2026-02-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_daily_banking_scalability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationbatch',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_qa', 'Pending QA'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', help_text='QA workflow status for this batch', max_length=20),
        ),
    ]
