# Generated by Django 5.2.9 on 2026-02-19 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_draft_status_to_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterbatch',
            name='failure_template',
            field=models.ForeignKey(blank=True, help_text='Template used for issue letters (failed payments). If blank, failed donations are skipped.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_letter_batches', to='core.lettertemplate'),
        ),
        migrations.AddField(
            model_name='lettertemplate',
            name='name',
            field=models.CharField(default='Template', help_text='User-defined name for this template', max_length=255),
        ),
        migrations.AddField(
            model_name='lettertemplate',
            name='template_type',
            field=models.CharField(choices=[('thank_you', 'Thank You Letter'), ('issue', 'Issue Letter')], db_index=True, default='thank_you', help_text='Type of letter: thank you (successful payments) or issue (failed payments)', max_length=20),
        ),
    ]
