# Generated by Django 5.2.9 on 2026-02-19 14:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_letter_template_dual_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('direct_debit', 'Direct Debit'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('caf', 'CAF Voucher/Card'), ('other_charity_voucher', 'Other Charity Voucher'), ('cheque', 'Cheque'), ('postal_order', 'Postal Order'), ('non_financial', 'Non Financial/No Payment')], help_text='All scans in this batch share this payment method', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_batches', to='core.campaign')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scan_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scan Batch',
                'verbose_name_plural': 'Scan Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanPlaceholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=1000)),
                ('image_path', models.CharField(help_text='Path in R2 bucket', max_length=500)),
                ('urn', models.CharField(blank=True, db_index=True, max_length=50)),
                ('donor_name', models.CharField(blank=True, max_length=255)),
                ('is_captured', models.BooleanField(db_index=True, default=False)),
                ('ocr_data', models.JSONField(blank=True, default=dict, help_text='Raw OCR results')),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholders', to='core.scanbatch')),
                ('donation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_placeholder', to='core.donation')),
            ],
            options={
                'verbose_name': 'Scan Placeholder',
                'verbose_name_plural': 'Scan Placeholders',
                'ordering': ['created_at'],
            },
        ),
    ]
