# Generated by Django 5.2.9 on 2026-02-23 14:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_scanbatch_scanplaceholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('sagepay', 'SagePay'), ('worldpay', 'WorldPay')], help_text='Payment provider type', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('config', models.JSONField(default=dict, help_text='Provider-specific configuration keys')),
                ('client', models.ForeignKey(help_text='Client associated with this configuration', on_delete=django.db.models.deletion.CASCADE, related_name='payment_configs', to='core.client')),
            ],
            options={
                'verbose_name': 'Payment Gateway Config',
                'verbose_name_plural': 'Payment Gateway Configs',
                'unique_together': {('client', 'provider')},
            },
        ),
    ]
