# Generated by Django 5.2.11 on 2026-02-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_paymentgatewayconfig'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaignfield',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='paymentgatewayconfig',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='serviceitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='donation',
            name='card_cvv',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='card_number',
        ),
        migrations.AddField(
            model_name='donation',
            name='card_last_four',
            field=models.CharField(blank=True, help_text='Last 4 digits of card number (PCI-DSS compliant — never store full card number)', max_length=4),
        ),
        migrations.AddConstraint(
            model_name='campaignfield',
            constraint=models.UniqueConstraint(fields=('campaign', 'label'), name='unique_campaign_field_label'),
        ),
        migrations.AddConstraint(
            model_name='paymentgatewayconfig',
            constraint=models.UniqueConstraint(fields=('client', 'provider'), name='unique_payment_gateway_client_provider'),
        ),
        migrations.AddConstraint(
            model_name='serviceitem',
            constraint=models.UniqueConstraint(fields=('category', 'description'), name='unique_service_item_category_description'),
        ),
    ]
