# Generated by Django 5.2.11 on 2026-02-25 00:53

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_campaignfield_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='bank_account_number',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Bank account number (encrypted at rest, up to 16 digits)', max_length=16),
        ),
        migrations.AlterField(
            model_name='donation',
            name='bank_sort_code',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='UK bank sort code (encrypted at rest, 6 digits, format: XX-XX-XX)', max_length=6),
        ),
    ]
