# Generated by Django 5.2.11 on 2026-02-25 00:55

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_donation_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='bank_account_number',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', help_text='Bank account number (encrypted at rest, up to 16 digits)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='bank_sort_code',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', help_text='UK bank sort code (encrypted at rest, 6 digits, format: XX-XX-XX)', max_length=6, null=True),
        ),
    ]
