# Generated by Django 5.2.11 on 2026-02-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_donation_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='donor_source',
            field=models.CharField(choices=[('house_file', 'House File'), ('data_file', 'Data File')], default='house_file', help_text='Donor lookup source: House File (global donors) or Data File (campaign-specific donors)', max_length=20),
        ),
    ]
