# Generated by Django 5.2.11 on 2026-02-25 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_donor_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanbatch',
            name='donation_batch',
            field=models.OneToOneField(blank=True, help_text='Auto-created DonationBatch from OCR results', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_batch', to='core.donationbatch'),
        ),
        migrations.AddField(
            model_name='scanbatch',
            name='matched_scans',
            field=models.PositiveIntegerField(default=0, help_text='Number of scans matched to a donor'),
        ),
        migrations.AddField(
            model_name='scanbatch',
            name='processed_scans',
            field=models.PositiveIntegerField(default=0, help_text='Number of scans processed by OCR'),
        ),
        migrations.AddField(
            model_name='scanbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='OCR processing status for this scan batch', max_length=20),
        ),
        migrations.AddField(
            model_name='scanbatch',
            name='total_scans',
            field=models.PositiveIntegerField(default=0, help_text='Total number of scans in this batch'),
        ),
        migrations.AddField(
            model_name='scanplaceholder',
            name='extracted_data',
            field=models.JSONField(blank=True, default=dict, help_text='Structured data extracted from OCR: {"amount": "25.00", "gift_aid": true, "payment_method": "cheque", "donation_date": "15/01/2026", "appeal_code": "...", ...}'),
        ),
        migrations.AddField(
            model_name='scanplaceholder',
            name='matched_data_file_donor',
            field=models.ForeignKey(blank=True, help_text='Data file donor matched via URN lookup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_placeholders', to='core.datafiledonor'),
        ),
        migrations.AddField(
            model_name='scanplaceholder',
            name='matched_donor',
            field=models.ForeignKey(blank=True, help_text='House file donor matched via URN lookup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_placeholders', to='core.donor'),
        ),
        migrations.AddField(
            model_name='scanplaceholder',
            name='ocr_confidence',
            field=models.FloatField(default=0.0, help_text='Overall OCR confidence score (0.0–1.0)'),
        ),
        migrations.AddField(
            model_name='scanplaceholder',
            name='ocr_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('matched', 'Matched'), ('unmatched', 'Unmatched')], db_index=True, default='pending', help_text='OCR processing status', max_length=20),
        ),
        migrations.AddField(
            model_name='scanplaceholder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scanplaceholder',
            name='ocr_data',
            field=models.JSONField(blank=True, default=dict, help_text='Raw OCR results from Google Cloud Vision'),
        ),
        migrations.AddIndex(
            model_name='scanbatch',
            index=models.Index(fields=['campaign', 'status'], name='scanbatch_camp_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='scanplaceholder',
            index=models.Index(fields=['batch', 'ocr_status'], name='scan_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='scanplaceholder',
            index=models.Index(fields=['urn', 'is_captured'], name='scan_urn_captured_idx'),
        ),
    ]
