# Generated by Django 5.2.11 on 2026-02-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_ocr_fields_to_scan_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='batch_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Batch identifier for bulk operations', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, default='', help_text='ID of the affected object', max_length=255),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_manager_emails',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of email addresses to notify for HGV donations'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, default='', help_text='Link to navigate to', max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_object_id',
            field=models.CharField(blank=True, default='', help_text='ID of related object', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(blank=True, default='', help_text='Model name of related object', max_length=50),
        ),
        migrations.AlterField(
            model_name='payinginslip',
            name='completion_status',
            field=models.CharField(blank=True, choices=[('full_success', 'Fully Processed'), ('partial_success', 'Partially Processed'), ('issues', 'Processed with Issues'), ('failed', 'Failed to Process')], default='', help_text='Processing outcome status', max_length=20),
        ),
        migrations.AlterField(
            model_name='scanplaceholder',
            name='ocr_confidence',
            field=models.FloatField(default=0.0, help_text='Overall OCR confidence score (0.0-1.0)'),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Customer phone number', max_length=50),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Payment description'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='error_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Stripe error code', max_length=100),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Error message if payment failed'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='error_type',
            field=models.CharField(blank=True, default='', help_text='Stripe error type', max_length=100),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='refund_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for refund'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='stripe_charge_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Stripe charge ID (starts with ch_)', max_length=255),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Stripe checkout session ID (starts with cs_)', max_length=255),
        ),
        migrations.AlterField(
            model_name='stripepaymentmethod',
            name='card_brand',
            field=models.CharField(blank=True, default='', help_text='Card brand (visa, mastercard, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='stripepaymentmethod',
            name='card_last4',
            field=models.CharField(blank=True, default='', help_text='Last 4 digits of card', max_length=4),
        ),
        migrations.AlterField(
            model_name='stripewebhookevent',
            name='processing_error',
            field=models.TextField(blank=True, default='', help_text='Error message if processing failed'),
        ),
    ]
