# Generated by Django 5.2.11 on 2026-02-26 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_auditlog_batch_id_alter_auditlog_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donor_name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='user_agent',
        ),
    ]
