# Generated by Django 5.2.11 on 2026-02-27 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_donor_uuid_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafiledonor',
            name='house_file_donor',
            field=models.ForeignKey(blank=True, help_text='Link to house file donor if exists', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_file_entries', to='core.donor'),
        ),
        migrations.AlterField(
            model_name='donationbatch',
            name='status',
            field=models.CharField(choices=[('pending_qa', 'Pending QA'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending_qa', help_text='QA workflow status for this batch', max_length=20),
        ),
        migrations.AlterField(
            model_name='scanplaceholder',
            name='matched_donor',
            field=models.ForeignKey(blank=True, help_text='House file donor matched via URN lookup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_placeholders', to='core.donor'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['urn'], name='core_donor_urn_82d02a_idx'),
        ),
    ]
