# Generated by Django 5.2.11 on 2026-02-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_draft_status_from_donationbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='document_ai_location',
            field=models.CharField(blank=True, default='eu', help_text="Document AI processor location (e.g. 'eu' or 'us'). Must match the region where the processor was created.", max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='document_ai_processor_id',
            field=models.CharField(blank=True, default='', help_text="Google Document AI processor ID for this charity's donation forms. Format: projects/{project}/locations/{location}/processors/{id}. Leave blank if Document AI is not yet configured for this client.", max_length=100),
        ),
        migrations.AddField(
            model_name='scanplaceholder',
            name='qr_decoded',
            field=models.BooleanField(db_index=True, default=False, help_text='True if a QR code was successfully decoded from the scan image. Warm records always have qr_decoded=True.'),
        ),
        migrations.AddField(
            model_name='scanplaceholder',
            name='qr_raw',
            field=models.CharField(blank=True, default='', help_text='Raw QR code string decoded from the scan (appeal_code|package_code|urn).', max_length=500),
        ),
    ]
