# Generated by Django 5.2.11 on 2026-03-01 11:44

from collections import defaultdict

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Count, Max


def backfill_donor_clients(apps, schema_editor):
    """Backfill client ownership for donor models using campaign-linked data."""
    DataFileDonor = apps.get_model('core', 'DataFileDonor')
    Donation = apps.get_model('core', 'Donation')
    Donor = apps.get_model('core', 'Donor')

    data_file_donors_to_update = list(
        DataFileDonor.objects.filter(
            client__isnull=True,
            data_file__campaign__client__isnull=False,
        ).select_related('data_file__campaign')
    )
    for data_file_donor in data_file_donors_to_update:
        data_file_donor.client_id = data_file_donor.data_file.campaign.client_id
    if data_file_donors_to_update:
        DataFileDonor.objects.bulk_update(data_file_donors_to_update, ['client'])

    donor_scores: dict[str, dict[str, dict[str, object]]] = defaultdict(dict)

    donation_candidates = (
        Donation.objects.filter(donor__isnull=False, campaign__client__isnull=False)
        .values('donor_id', 'campaign__client_id')
        .annotate(client_count=Count('id'), latest_activity=Max('created_at'))
    )
    for row in donation_candidates:
        donor_id = str(row['donor_id'])
        client_id = str(row['campaign__client_id'])
        donor_scores[donor_id][client_id] = {
            'count': row['client_count'],
            'latest': row['latest_activity'],
        }

    data_file_candidates = (
        DataFileDonor.objects.filter(
            house_file_donor__isnull=False,
            data_file__campaign__client__isnull=False,
        )
        .values('house_file_donor_id', 'data_file__campaign__client_id')
        .annotate(client_count=Count('id'), latest_activity=Max('created_at'))
    )
    for row in data_file_candidates:
        donor_id = str(row['house_file_donor_id'])
        client_id = str(row['data_file__campaign__client_id'])
        existing = donor_scores[donor_id].get(client_id)
        if existing:
            existing_count = int(existing['count'])
            existing_latest = existing['latest']
            new_count = existing_count + row['client_count']
            new_latest = existing_latest
            if existing_latest is None or (
                row['latest_activity'] and row['latest_activity'] > existing_latest
            ):
                new_latest = row['latest_activity']
            donor_scores[donor_id][client_id] = {
                'count': new_count,
                'latest': new_latest,
            }
        else:
            donor_scores[donor_id][client_id] = {
                'count': row['client_count'],
                'latest': row['latest_activity'],
            }

    donors_to_update = []
    for donor in Donor.objects.filter(client__isnull=True).only('id'):
        client_scores = donor_scores.get(str(donor.id))
        if not client_scores:
            continue
        best_client_id = max(
            client_scores.items(),
            key=lambda item: (
                int(item[1]['count']),
                item[1]['latest'].timestamp() if item[1]['latest'] else float('-inf'),
                item[0],
            ),
        )[0]
        donor.client_id = best_client_id
        donors_to_update.append(donor)

    if donors_to_update:
        Donor.objects.bulk_update(donors_to_update, ['client'])


def noop_reverse(apps, schema_editor):
    """No-op reverse migration for backfill data operation."""
    return


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_document_ai_and_qr_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafiledonor',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client/charity this donor belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_file_donors', to='core.client'),
        ),
        migrations.AddField(
            model_name='donor',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client/charity this donor belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='core.client'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='urn',
            field=models.CharField(blank=True, help_text='Unique Reference Number from the charity. Null for new donors captured before the charity assigns a URN.', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='datafiledonor',
            index=models.Index(fields=['client', 'urn'], name='core_datafi_client__9ad37f_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['client', 'urn'], name='core_donor_client__571817_idx'),
        ),
        migrations.RunPython(backfill_donor_clients, noop_reverse),
        migrations.AddConstraint(
            model_name='donor',
            constraint=models.UniqueConstraint(fields=('client', 'urn'), name='unique_donor_urn_per_client'),
        ),
    ]
