# Generated by Django 5.2.11 on 2026-03-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_datafiledonor_client_donor_client_alter_donor_urn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Short uppercase code for this client (e.g. 'BRC' for British Red Cross). Used as the first folder segment in R2 scan paths: ScanOutput/{client_code}/{appeal_code}/{payment_method}/. Use uppercase letters/digits only, no spaces.", max_length=20),
        ),
    ]
