# Generated by Django 5.2.11 on 2026-03-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_client_code_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='form_field_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='JSON mapping of this charity\'s form field labels to canonical extraction field names.  Keys are the verbatim label text from the donation form (lowercased, spaces OK).  Values are canonical field names such as donor_name, amount, gift_aid, postcode, phone, email, address_block, contact_consent, email_consent, sms_consent, phone_consent, post_consent.  \n\nExample (raffle form):\n{"full name": "donor_name", "i would like to purchase £": "amount", "i am a uk taxpayer": "gift_aid"}\n\nUniversal NLP types (person, address, phone, email) are detected automatically and do NOT need to be listed here.'),
        ),
    ]
