# Generated by Django 5.2.11 on 2026-03-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_client_form_field_mapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='bank_account_name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='bank_reference',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='bank_sort_code',
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('direct_debit', 'Direct Debit'), ('cash', 'Cash'), ('caf', 'CAF Voucher/Card'), ('other_charity_voucher', 'Other Charity Voucher'), ('cheque', 'Cheque'), ('postal_order', 'Postal Order'), ('non_financial', 'Non Financial/No Payment')], default='card', help_text='Payment method used', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cheque', 'Cheque'), ('cash', 'Cash'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scanbatch',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('direct_debit', 'Direct Debit'), ('cash', 'Cash'), ('caf', 'CAF Voucher/Card'), ('other_charity_voucher', 'Other Charity Voucher'), ('cheque', 'Cheque'), ('postal_order', 'Postal Order'), ('non_financial', 'Non Financial/No Payment')], help_text='All scans in this batch share this payment method', max_length=30),
        ),
    ]
