# Generated by Django 5.2.11 on 2026-03-12 19:19

from django.db import migrations, models


def _build_unique_batch_name(base_name: str, existing_names: set[str], index: int) -> str:
    """Return a unique legacy batch name that fits the field length."""

    suffix = f" [legacy {index}]"
    max_base_length = 255 - len(suffix)
    truncated_base = base_name[:max_base_length].rstrip() or "legacy-batch"
    candidate = f"{truncated_base}{suffix}"
    while candidate in existing_names:
        index += 1
        suffix = f" [legacy {index}]"
        max_base_length = 255 - len(suffix)
        truncated_base = base_name[:max_base_length].rstrip() or "legacy-batch"
        candidate = f"{truncated_base}{suffix}"
    return candidate


def deduplicate_existing_batch_names(apps, schema_editor):
    """Rename legacy duplicate batch names before uniqueness constraints apply."""

    donation_batch_model = apps.get_model('core', 'DonationBatch')
    scan_batch_model = apps.get_model('core', 'ScanBatch')

    for model in (donation_batch_model, scan_batch_model):
        campaign_ids = model.objects.values_list('campaign_id', flat=True).distinct()
        for campaign_id in campaign_ids:
            batches = list(
                model.objects.filter(campaign_id=campaign_id).order_by('batch_name', 'id')
            )
            existing_names = {str(batch.batch_name) for batch in batches}
            seen_names: dict[str, int] = {}
            for batch in batches:
                base_name = str(batch.batch_name)
                seen_count = seen_names.get(base_name, 0) + 1
                seen_names[base_name] = seen_count
                if seen_count == 1:
                    continue

                existing_names.discard(base_name)
                unique_name = _build_unique_batch_name(base_name, existing_names, seen_count)
                batch.batch_name = unique_name
                batch.save(update_fields=['batch_name'])
                existing_names.add(unique_name)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_scanplaceholder_ocr_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanbatch',
            name='source_filename',
            field=models.CharField(blank=True, default='', help_text='Original uploaded PDF filename for this physical batch', max_length=255),
        ),
        migrations.AlterField(
            model_name='scanbatch',
            name='batch_name',
            field=models.CharField(help_text='Canonical physical batch identifier derived from the upload filename', max_length=255),
        ),
        migrations.RunPython(deduplicate_existing_batch_names, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='donationbatch',
            constraint=models.UniqueConstraint(fields=('campaign', 'batch_name'), name='donationbatch_campaign_batch_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='scanbatch',
            constraint=models.UniqueConstraint(fields=('campaign', 'batch_name'), name='scanbatch_campaign_batch_name_uniq'),
        ),
    ]
