# Generated by Django 5.2.11 on 2026-03-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_scanbatch_source_filename_alter_scanbatch_batch_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='letterbatch',
            constraint=models.UniqueConstraint(fields=('campaign', 'batch_number'), name='unique_campaign_batch_number'),
        ),
    ]