# Generated by Django 5.2.11 on 2026-03-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_letterbatch_campaign_batch_number_constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='scanbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_method__in', ('card', 'direct_debit', 'cash', 'non_financial')), ('scan_form_type__in', ('simplex', 'duplex', 'mixed_mail'))), models.Q(('payment_method__in', ('cheque', 'caf', 'other_charity_voucher', 'postal_order')), ('scan_form_type__in', ('simplex_with_payment', 'duplex_with_payment', 'mixed_mail'))), _connector='OR'), name='scanbatch_pay_method_form_type_compat'),
        ),
    ]
