# Generated by Django 5.2.11 on 2026-03-20 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_add_package_code_to_datafiledonor'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='datafiledonor',
            new_name='core_datafi_package_c28584_idx',
            old_name='core_datafiledonor_package_code_idx',
        ),
    ]
