# Generated by Django 5.2.11 on 2026-03-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_rename_core_datafiledonor_package_code_idx_core_datafi_package_c28584_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanbatch',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Error description when this batch failed to process'),
        ),
    ]
