# Generated by Django 5.2 on 2026-03-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_scan_batch_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanplaceholder',
            name='donor_pdf_key',
            field=models.CharField(
                blank=True,
                default='',
                max_length=1000,
                help_text=(
                    'R2 key for the assembled per-donor PDF (all pages merged into one file). '
                    'Used by the client portal to serve a viewable copy of the donor\'s form.'
                ),
            ),
        ),
    ]
