# Generated by Django 5.2.11 on 2026-03-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_scanplaceholder_donor_pdf_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('partially_completed', 'Partially Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='OCR processing status for this scan batch', max_length=20),
        ),
    ]
