# Generated by Django 5.2.11 on 2026-03-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_scanbatch_add_partially_completed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationbatch',
            name='field_data',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible metadata and generated artefact paths for this batch'),
        ),
    ]
