# Generated by Django 5.2.11 on 2026-03-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_donationbatch_add_field_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationbatch',
            name='gift_aid_report_path',
            field=models.CharField(blank=True, default='', help_text='Media-relative path to the generated HMRC Gift Aid CSV for this batch', max_length=500),
        ),
    ]
