# Generated by Django 5.2.11 on 2026-03-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_donationbatch_add_gift_aid_report_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafiledonor',
            name='address_last_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the donor address was last confirmed or corrected', null=True),
        ),
        migrations.AddField(
            model_name='datafiledonor',
            name='contact_status',
            field=models.CharField(choices=[('normal', 'Normal'), ('gone_away', 'Gone Away'), ('deceased', 'Deceased'), ('bad_address', 'Bad Address'), ('temporarily_suppressed', 'Temporarily Suppressed')], default='normal', help_text='Operational contactability status for donor servicing and postal suppression.', max_length=30),
        ),
        migrations.AddField(
            model_name='datafiledonor',
            name='contact_status_changed_at',
            field=models.DateTimeField(blank=True, help_text="When the donor's current contact status was last changed", null=True),
        ),
        migrations.AddField(
            model_name='datafiledonor',
            name='contact_status_reason',
            field=models.CharField(blank=True, help_text="Reason or source for the donor's current contact status", max_length=255),
        ),
        migrations.AddField(
            model_name='donor',
            name='address_last_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the donor address was last confirmed or corrected', null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='contact_status',
            field=models.CharField(choices=[('normal', 'Normal'), ('gone_away', 'Gone Away'), ('deceased', 'Deceased'), ('bad_address', 'Bad Address'), ('temporarily_suppressed', 'Temporarily Suppressed')], default='normal', help_text='Operational contactability status for donor servicing and postal suppression.', max_length=30),
        ),
        migrations.AddField(
            model_name='donor',
            name='contact_status_changed_at',
            field=models.DateTimeField(blank=True, help_text="When the donor's current contact status was last changed", null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='contact_status_reason',
            field=models.CharField(blank=True, help_text="Reason or source for the donor's current contact status", max_length=255),
        ),
        migrations.AddIndex(
            model_name='datafiledonor',
            index=models.Index(fields=['contact_status'], name='core_datafi_contact_50dd24_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['contact_status'], name='core_donor_contact_90bc85_idx'),
        ),
    ]
