# Generated by Django 5.2.11 on 2026-03-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_datafiledonor_address_last_verified_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="form_field_mapping",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "JSON mapping of this charity's form field labels to canonical "
                    "extraction field names.  Keys are the verbatim label text from the "
                    "donation form (lowercased, spaces OK).  Values are canonical field "
                    "names such as donor_name, donor_first_name, donor_last_name, amount, "
                    "gift_aid, address_line1, address_line2, city, postcode, phone, "
                    "email, address_block, contact_consent, email_consent, sms_consent, "
                    "phone_consent, post_consent.  \n\n"
                    "Example (raffle form):\n"
                    '{"full name": "donor_name", "i would like to purchase £": "amount", '
                    '"i am a uk taxpayer": "gift_aid"}\n\n'
                    "Universal NLP types (person, address, phone, email) are detected "
                    "automatically and do NOT need to be listed here."
                ),
            ),
        ),
    ]