# Generated by Django 5.2.11 on 2026-03-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_alter_scanbatch_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="datafiledonor",
            name="gift_aid_date",
            field=models.DateField(
                blank=True,
                help_text="Date the donor made their Gift Aid declaration",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="datafiledonor",
            name="gift_aid_declaration",
            field=models.BooleanField(
                default=False,
                help_text="Whether the donor has made a Gift Aid declaration",
            ),
        ),
        migrations.AddField(
            model_name="donor",
            name="gift_aid_date",
            field=models.DateField(
                blank=True,
                help_text="Date the donor made their Gift Aid declaration",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="donor",
            name="gift_aid_declaration",
            field=models.BooleanField(
                default=False,
                help_text="Whether the donor has made a Gift Aid declaration",
            ),
        ),
    ]