# Generated by Django 5.2.11 on 2026-03-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_alter_campaign_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Card"),
                    ("direct_debit", "Direct Debit"),
                    ("cash", "Cash"),
                    ("caf", "CAF Voucher"),
                    ("other_charity_voucher", "Other Charity Voucher"),
                    ("cheque", "Cheque"),
                    ("postal_order", "Postal Order"),
                    ("non_financial", "Non Financial/No Payment"),
                ],
                default="card",
                help_text="Payment method used",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="scanbatch",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Card"),
                    ("direct_debit", "Direct Debit"),
                    ("cash", "Cash"),
                    ("caf", "CAF Voucher"),
                    ("other_charity_voucher", "Other Charity Voucher"),
                    ("cheque", "Cheque"),
                    ("postal_order", "Postal Order"),
                    ("non_financial", "Non Financial/No Payment"),
                ],
                help_text="All scans in this batch share this payment method",
                max_length=30,
            ),
        ),
    ]