# Generated by Django 5.2.11 on 2026-03-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_caf_payment_method_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafiledonor',
            name='no_thank_you',
            field=models.BooleanField(default=False, help_text='Donor has opted out of thank-you communications.'),
        ),
    ]
