# Generated by Django 5.2.11 on 2026-03-27 23:31

from django.db import migrations, models


def purge_other_charity_voucher_records(apps: object, schema_editor: object) -> None:
    """Delete legacy other-charity-voucher records before tightening choices."""
    del schema_editor
    Donation = apps.get_model("core", "Donation")
    PayingInSlip = apps.get_model("core", "PayingInSlip")
    ScanBatch = apps.get_model("core", "ScanBatch")
    DonationBatch = apps.get_model("core", "DonationBatch")

    Donation.objects.filter(payment_method="other_charity_voucher").delete()
    PayingInSlip.objects.filter(payment_type="other_charity_voucher").delete()
    ScanBatch.objects.filter(payment_method="other_charity_voucher").delete()
    DonationBatch.objects.filter(default_payment_method="other_charity_voucher").update(
        default_payment_method="cheque"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_datafiledonor_no_thank_you'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scanbatch',
            name='scanbatch_pay_method_form_type_compat',
        ),
        migrations.RunPython(
            code=purge_other_charity_voucher_records,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='donation',
            name='other_charity_name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='other_charity_voucher_amount',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='other_charity_voucher_number',
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('direct_debit', 'Direct Debit'), ('cash', 'Cash'), ('caf', 'CAF Voucher'), ('cheque', 'Cheque'), ('postal_order', 'Postal Order'), ('non_financial', 'Non Financial/No Payment')], default='card', help_text='Payment method used', max_length=30),
        ),
        migrations.AlterField(
            model_name='payinginslip',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('postal_order', 'Postal Order'), ('caf', 'CAF Voucher'), ('mixed', 'Mixed')], default='mixed', help_text='Type of payments in this slip', max_length=30),
        ),
        migrations.AlterField(
            model_name='scanbatch',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('direct_debit', 'Direct Debit'), ('cash', 'Cash'), ('caf', 'CAF Voucher'), ('cheque', 'Cheque'), ('postal_order', 'Postal Order'), ('non_financial', 'Non Financial/No Payment')], help_text='All scans in this batch share this payment method', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='scanbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_method__in', ('card', 'direct_debit', 'cash', 'non_financial')), ('scan_form_type__in', ('simplex', 'duplex', 'mixed_mail'))), models.Q(('payment_method__in', ('cheque', 'caf', 'postal_order')), ('scan_form_type__in', ('simplex_with_payment', 'duplex_with_payment', 'mixed_mail'))), _connector='OR'), name='scanbatch_pay_method_form_type_compat'),
        ),
    ]
