# Generated by Django 5.2.11 on 2026-04-01 18:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_system_donors(apps: object, schema_editor: object) -> None:
    """Create internal donor profiles for existing source-linked donations."""
    Donor = apps.get_model("core", "Donor")
    DataFileDonor = apps.get_model("core", "DataFileDonor")
    Donation = apps.get_model("core", "Donation")
    SystemDonor = apps.get_model("core", "SystemDonor")

    system_donor_ids_by_key: dict[tuple[str | None, str], uuid.UUID] = {}

    for donor in Donor.objects.all().iterator():
        external_urn = donor.urn or ""
        key = (str(donor.client_id) if donor.client_id else None, external_urn or str(donor.id))
        system_donor = SystemDonor.objects.create(
            client_id=donor.client_id,
            external_urn=external_urn,
            title=donor.title,
            first_name=donor.first_name,
            last_name=donor.last_name,
            email=donor.email,
            phone=donor.phone,
            address_line1=donor.address_line1,
            address_line2=donor.address_line2,
            city=donor.city,
            county=donor.county,
            postcode=donor.postcode,
            country=donor.country,
            date_of_birth=donor.date_of_birth,
            age=donor.age,
            gift_aid_declaration=donor.gift_aid_declaration,
            gift_aid_date=donor.gift_aid_date,
            contact_status=donor.contact_status,
            contact_status_reason=donor.contact_status_reason,
            contact_status_changed_at=donor.contact_status_changed_at,
            address_last_verified_at=donor.address_last_verified_at,
            consent_contact=donor.consent_contact,
            opt_in_email=donor.opt_in_email,
            opt_in_sms=donor.opt_in_sms,
            opt_in_phone=donor.opt_in_phone,
            opt_in_post=donor.opt_in_post,
            source_snapshot={
                "source_type": "house_file",
                "source_donor_id": str(donor.pk),
                "external_urn": external_urn,
            },
            created_by_id=donor.created_by_id,
        )
        system_donor_ids_by_key[key] = system_donor.pk

    for source in DataFileDonor.objects.select_related("data_file__campaign").all().iterator():
        external_urn = source.urn or ""
        client_id = source.client_id or source.data_file.campaign.client_id
        key = (str(client_id) if client_id else None, external_urn or str(source.id))
        if key in system_donor_ids_by_key:
            continue
        system_donor = SystemDonor.objects.create(
            client_id=client_id,
            external_urn=external_urn,
            title=source.title,
            first_name=source.first_name,
            last_name=source.last_name,
            email=source.email,
            phone=source.phone,
            address_line1=source.address_line1,
            address_line2=source.address_line2,
            city=source.city,
            county=source.county,
            postcode=source.postcode,
            country=source.country,
            date_of_birth=source.date_of_birth,
            age=source.age,
            gift_aid_declaration=source.gift_aid_declaration,
            gift_aid_date=source.gift_aid_date,
            contact_status=source.contact_status,
            contact_status_reason=source.contact_status_reason,
            contact_status_changed_at=source.contact_status_changed_at,
            address_last_verified_at=source.address_last_verified_at,
            consent_contact=source.consent_contact,
            opt_in_email=source.opt_in_email,
            opt_in_sms=source.opt_in_sms,
            opt_in_phone=source.opt_in_phone,
            opt_in_post=source.opt_in_post,
            source_snapshot={
                "source_type": "data_file",
                "source_donor_id": str(source.pk),
                "external_urn": external_urn,
            },
            created_by_id=source.created_by_id,
        )
        system_donor_ids_by_key[key] = system_donor.pk

    for donation in Donation.objects.select_related(
        "donor",
        "data_file_donor",
        "campaign",
    ).all().iterator():
        if donation.system_donor_id:
            continue
        source = donation.donor or donation.data_file_donor
        if source is None:
            continue
        external_urn = getattr(source, "urn", "") or ""
        key = (
            str(donation.campaign.client_id) if donation.campaign_id else None,
            external_urn or str(source.pk),
        )
        system_donor_id = system_donor_ids_by_key.get(key)
        if system_donor_id is None:
            continue
        donation.system_donor_id = system_donor_id
        donation.save(update_fields=["system_donor"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_scanplaceholder_manual_redaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='data_file_donor',
            field=models.ForeignKey(blank=True, help_text='Matched imported campaign data-file donor source row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='core.datafiledonor'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(blank=True, help_text='Matched imported house-file donor source row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='core.donor'),
        ),
        migrations.CreateModel(
            name='SystemDonor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='System-generated unique identifier for the internal donor profile', primary_key=True, serialize=False)),
                ('external_urn', models.CharField(blank=True, default='', help_text='Latest known source-system URN for this donor, when available', max_length=50)),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Rev', 'Rev'), ('Sir', 'Sir'), ('Lady', 'Lady'), ('Other', 'Other')], max_length=10)),
                ('first_name', models.CharField(help_text='Donor first name', max_length=100)),
                ('last_name', models.CharField(help_text='Donor last name', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20)),
                ('address_line1', models.CharField(blank=True, help_text='Address Line 1', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Address Line 2', max_length=255)),
                ('city', models.CharField(blank=True, help_text='City', max_length=100)),
                ('county', models.CharField(blank=True, help_text='County', max_length=100)),
                ('postcode', models.CharField(blank=True, help_text='UK Postcode', max_length=20)),
                ('country', models.CharField(default='United Kingdom', help_text='Country', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('age', models.PositiveIntegerField(blank=True, help_text='Age (if date of birth is not available)', null=True)),
                ('gift_aid_declaration', models.BooleanField(default=False, help_text='Whether the donor has made a Gift Aid declaration')),
                ('gift_aid_date', models.DateField(blank=True, help_text='Date the donor made their Gift Aid declaration', null=True)),
                ('contact_status', models.CharField(choices=[('normal', 'Normal'), ('gone_away', 'Gone Away'), ('deceased', 'Deceased'), ('bad_address', 'Bad Address'), ('temporarily_suppressed', 'Temporarily Suppressed')], default='normal', help_text='Operational contactability status for donor servicing', max_length=30)),
                ('contact_status_reason', models.CharField(blank=True, help_text="Reason or source for the donor's current contact status", max_length=255)),
                ('contact_status_changed_at', models.DateTimeField(blank=True, help_text="When the donor's current contact status was last changed", null=True)),
                ('address_last_verified_at', models.DateTimeField(blank=True, help_text='When the donor address was last confirmed or corrected', null=True)),
                ('consent_contact', models.BooleanField(default=False, help_text='Consents to being contacted by charity')),
                ('opt_in_email', models.BooleanField(default=False, help_text='Opt-in for email contact')),
                ('opt_in_sms', models.BooleanField(default=False, help_text='Opt-in for SMS contact')),
                ('opt_in_phone', models.BooleanField(default=False, help_text='Opt-in for phone contact')),
                ('opt_in_post', models.BooleanField(default=False, help_text='Opt-in for postal contact')),
                ('source_snapshot', models.JSONField(blank=True, default=dict, help_text='Latest imported or OCR-derived donor snapshot used for upsert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, help_text='Client/charity this internal donor belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_donors', to='core.client')),
                ('created_by', models.ForeignKey(help_text='User who first created this internal donor profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_donors_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Donor',
                'verbose_name_plural': 'System Donors',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='system_donor',
            field=models.ForeignKey(blank=True, help_text='Permanent internal donor profile for donation history', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='core.systemdonor'),
        ),
        migrations.AddField(
            model_name='scanplaceholder',
            name='matched_system_donor',
            field=models.ForeignKey(blank=True, help_text='Internal donor profile created or resolved for this scan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_placeholders', to='core.systemdonor'),
        ),
        migrations.RunPython(backfill_system_donors, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['system_donor'], name='donation_system_donor_idx'),
        ),
        migrations.AddIndex(
            model_name='systemdonor',
            index=models.Index(fields=['client', 'external_urn'], name='core_system_client__f6a3bf_idx'),
        ),
        migrations.AddIndex(
            model_name='systemdonor',
            index=models.Index(fields=['client', 'last_name', 'first_name'], name='core_system_client__82a10f_idx'),
        ),
        migrations.AddIndex(
            model_name='systemdonor',
            index=models.Index(fields=['email'], name='core_system_email_9b871c_idx'),
        ),
        migrations.AddIndex(
            model_name='systemdonor',
            index=models.Index(fields=['phone'], name='core_system_phone_77d3f7_idx'),
        ),
        migrations.AddIndex(
            model_name='systemdonor',
            index=models.Index(fields=['postcode'], name='core_system_postcod_2bbc9a_idx'),
        ),
        migrations.AddIndex(
            model_name='systemdonor',
            index=models.Index(fields=['contact_status'], name='core_system_contact_1835eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='systemdonor',
            constraint=models.UniqueConstraint(fields=('client', 'external_urn'), name='unique_system_donor_external_urn_per_client'),
        ),
    ]
