# Generated by Django 5.2.13 on 2026-04-19 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_remove_letters_state_only'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='invoice',
                    name='campaign',
                ),
                migrations.RemoveField(
                    model_name='invoice',
                    name='client',
                ),
                migrations.RemoveField(
                    model_name='invoice',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='invoice',
                    name='donations',
                ),
            ],
            database_operations=[],
        ),
    ]
