# Generated by Django 5.2.13 on 2026-04-19 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_remove_invoice_fks_state_only'),
        ('invoices', '0001_initial_state_only'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='stripepayment',
                    name='invoice',
                    field=models.ForeignKey(blank=True, help_text='Invoice being paid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_payments', to='invoices.invoice'),
                ),
                migrations.RemoveField(
                    model_name='invoicesettings',
                    name='updated_by',
                ),
                migrations.RemoveField(
                    model_name='serviceitem',
                    name='category',
                ),
                migrations.DeleteModel(
                    name='Invoice',
                ),
                migrations.DeleteModel(
                    name='InvoiceSettings',
                ),
                migrations.DeleteModel(
                    name='ServiceCategory',
                ),
                migrations.DeleteModel(
                    name='ServiceItem',
                ),
            ],
            database_operations=[],
        ),
    ]
