# Generated by Django 5.2.13 on 2026-04-19 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_remove_invoices_state_only'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='auditlog',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='exportlog',
                    name='campaign',
                ),
                migrations.RemoveField(
                    model_name='exportlog',
                    name='requested_by',
                ),
                migrations.DeleteModel(
                    name='ApprovalLog',
                ),
                migrations.DeleteModel(
                    name='AuditLog',
                ),
                migrations.DeleteModel(
                    name='ExportLog',
                ),
            ],
            database_operations=[],
        ),
    ]
