# Generated by Django 5.2.13 on 2026-04-19 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial_state_only'),
        ('core', '0066_remove_audit_state_only'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='stripecustomer',
                    name='client',
                    field=models.ForeignKey(blank=True, help_text='Linked charity/client organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_customers', to='clients.client'),
                ),
                migrations.RemoveField(
                    model_name='clientportaluser',
                    name='client',
                ),
                migrations.AlterField(
                    model_name='campaign',
                    name='client',
                    field=models.ForeignKey(help_text='Client/charity this campaign belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='clients.client'),
                ),
                migrations.AlterField(
                    model_name='datafiledonor',
                    name='client',
                    field=models.ForeignKey(blank=True, help_text='Client/charity this donor belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_file_donors', to='clients.client'),
                ),
                migrations.AlterField(
                    model_name='systemdonor',
                    name='client',
                    field=models.ForeignKey(blank=True, help_text='Client/charity this internal donor belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_donors', to='clients.client'),
                ),
                migrations.AlterField(
                    model_name='paymentgatewayconfig',
                    name='client',
                    field=models.ForeignKey(help_text='Client associated with this configuration', on_delete=django.db.models.deletion.CASCADE, related_name='payment_configs', to='clients.client'),
                ),
                migrations.AlterField(
                    model_name='donor',
                    name='client',
                    field=models.ForeignKey(blank=True, help_text='Client/charity this donor belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='clients.client'),
                ),
                migrations.RemoveField(
                    model_name='clientportaluser',
                    name='invited_by',
                ),
                migrations.RemoveField(
                    model_name='clientportaluser',
                    name='user',
                ),
            ],
            database_operations=[],
        ),
    ]
