# Generated by Django 5.2.13 on 2026-04-19 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_remove_client_state_only'),
        ('core', '0067_remove_client_state_only'),
        ('invoices', '0002_remove_client_state_only'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Client',
                ),
                migrations.DeleteModel(
                    name='ClientPortalUser',
                ),
            ],
            database_operations=[],
        ),
    ]
