# Generated by Django 5.2.13 on 2026-04-19 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_add_campaign_models_state_only'),
        ('core', '0068_remove_client_state_only'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='campaign',
                    name='client',
                ),
                migrations.RemoveField(
                    model_name='campaign',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='campaign',
                    name='package_codes',
                ),
                migrations.RemoveField(
                    model_name='campaign',
                    name='payment_processed_by',
                ),
                migrations.AlterField(
                    model_name='segment',
                    name='campaign',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign'),
                ),
                migrations.RemoveField(
                    model_name='campaignfield',
                    name='campaign',
                ),
                migrations.AlterField(
                    model_name='campaigndatafile',
                    name='campaign',
                    field=models.OneToOneField(help_text='Campaign this data file belongs to', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='data_file', serialize=False, to='campaigns.campaign'),
                ),
                migrations.AlterField(
                    model_name='donation',
                    name='campaign',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='campaigns.campaign'),
                ),
                migrations.AlterField(
                    model_name='scanuploadprogress',
                    name='campaign',
                    field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='scan_progress', serialize=False, to='campaigns.campaign'),
                ),
                migrations.AlterField(
                    model_name='donationbatch',
                    name='campaign',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_batches', to='campaigns.campaign'),
                ),
                migrations.AlterField(
                    model_name='scanbatch',
                    name='campaign',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_batches', to='campaigns.campaign'),
                ),
                migrations.AlterField(
                    model_name='donorupload',
                    name='campaign',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign'),
                ),
                migrations.AlterField(
                    model_name='donation',
                    name='package_codes',
                    field=models.ManyToManyField(blank=True, help_text='Package codes associated with this donation', related_name='donations', to='campaigns.packagecode'),
                ),
                migrations.DeleteModel(
                    name='PackageCode',
                ),
                migrations.DeleteModel(
                    name='CampaignField',
                ),
            ],
            database_operations=[],
        ),
    ]
