# Generated by Django 5.2.13 on 2026-04-19 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_approvallog_campaign_alter_exportlog_campaign'),
        ('core', '0069_remove_campaign_client_remove_campaign_created_by_and_more'),
        ('invoices', '0003_alter_invoice_campaign'),
        ('letters', '0002_alter_letterbatch_campaign_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Campaign',
                ),
            ],
            database_operations=[],
        ),
    ]
