# Generated by Django 5.2.13 on 2026-04-19 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_delete_campaign'),
        ('donors', '0001_initial_state_only'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='donation',
                    name='donor',
                    field=models.ForeignKey(blank=True, help_text='Matched imported house-file donor source row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donors.donor'),
                ),
                migrations.AlterField(
                    model_name='stripecustomer',
                    name='donor',
                    field=models.ForeignKey(blank=True, help_text='Linked donor for donation payments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_customers', to='donors.donor'),
                ),
                migrations.AlterField(
                    model_name='datafiledonor',
                    name='house_file_donor',
                    field=models.ForeignKey(blank=True, help_text='Link to house file donor if exists', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_file_entries', to='donors.donor'),
                ),
                migrations.AlterField(
                    model_name='scanplaceholder',
                    name='matched_donor',
                    field=models.ForeignKey(blank=True, help_text='House file donor matched via URN lookup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_placeholders', to='donors.donor'),
                ),
                migrations.RemoveField(
                    model_name='donorupload',
                    name='campaign',
                ),
                migrations.RemoveField(
                    model_name='donorupload',
                    name='uploaded_by',
                ),
                migrations.RemoveField(
                    model_name='segment',
                    name='campaign',
                ),
                migrations.RemoveField(
                    model_name='systemdonor',
                    name='client',
                ),
                migrations.RemoveField(
                    model_name='systemdonor',
                    name='created_by',
                ),
                migrations.AlterField(
                    model_name='donation',
                    name='system_donor',
                    field=models.ForeignKey(blank=True, help_text='Permanent internal donor profile for donation history', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='donors.systemdonor'),
                ),
                migrations.AlterField(
                    model_name='scanplaceholder',
                    name='matched_system_donor',
                    field=models.ForeignKey(blank=True, help_text='Internal donor profile created or resolved for this scan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_placeholders', to='donors.systemdonor'),
                ),
                migrations.DeleteModel(
                    name='Donor',
                ),
                migrations.DeleteModel(
                    name='DonorUpload',
                ),
                migrations.DeleteModel(
                    name='Segment',
                ),
                migrations.DeleteModel(
                    name='SystemDonor',
                ),
            ],
            database_operations=[],
        ),
    ]
