# Generated by Django 5.2.13 on 2026-04-19 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_donation_donor_alter_stripecustomer_donor_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='campaigndatafile',
                    name='campaign',
                ),
                migrations.RemoveField(
                    model_name='campaigndatafile',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='datafiledonor',
                    name='data_file',
                ),
                migrations.RemoveField(
                    model_name='datafileupload',
                    name='data_file',
                ),
                migrations.RemoveField(
                    model_name='datafiledonor',
                    name='client',
                ),
                migrations.RemoveField(
                    model_name='datafiledonor',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='datafiledonor',
                    name='house_file_donor',
                ),
            ],
            database_operations=[],
        ),
    ]
