# Generated by Django 5.2.13 on 2026-04-19 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_remove_campaigndatafile_campaign_and_more'),
        ('donors', '0002_datafiledonor'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='donation',
                    name='data_file_donor',
                    field=models.ForeignKey(blank=True, help_text='Matched imported campaign data-file donor source row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donors.datafiledonor'),
                ),
                migrations.AlterField(
                    model_name='scanplaceholder',
                    name='matched_data_file_donor',
                    field=models.ForeignKey(blank=True, help_text='Data file donor matched via URN lookup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_placeholders', to='donors.datafiledonor'),
                ),
                migrations.RemoveField(
                    model_name='datafileupload',
                    name='uploaded_by',
                ),
                migrations.DeleteModel(
                    name='CampaignDataFile',
                ),
                migrations.DeleteModel(
                    name='DataFileDonor',
                ),
                migrations.DeleteModel(
                    name='DataFileUpload',
                ),
            ],
            database_operations=[],
        ),
    ]
