# Generated by Django 5.2.13 on 2026-04-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_remove_scanplaceholder_donation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Optional profile avatar.', null=True, upload_to='profile_images/'),
        ),
    ]
