# Generated by Django 5.2.13 on 2026-04-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='When True, the user is redirected to the change-password screen before they can access any other page. Set automatically when an admin creates or resets the account.'),
        ),
    ]
