# Generated by Django 5.2.13 on 2026-04-25 16:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_qa_reject_reason'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePaymentAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, default='', help_text='Stripe PaymentIntent ID (blank if Stripe returned no intent)', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('requires_action', 'Requires Action')], db_index=True, help_text='Outcome of the attempt', max_length=30)),
                ('error_code', models.CharField(blank=True, default='', help_text='Stripe error code, if any', max_length=100)),
                ('error_message', models.TextField(blank=True, default='', help_text='Stripe error message, if any')),
                ('amount_cents', models.PositiveIntegerField(help_text='Amount in minor units (e.g. pence)')),
                ('currency', models.CharField(default='GBP', help_text='3-letter ISO currency code', max_length=3)),
                ('attempt_number', models.PositiveSmallIntegerField(help_text='1-based attempt counter per donation')),
                ('donation', models.ForeignKey(help_text='Donation the attempt was made for', on_delete=django.db.models.deletion.CASCADE, related_name='stripe_attempts', to='donations.donation')),
            ],
            options={
                'verbose_name': 'Stripe Payment Attempt',
                'verbose_name_plural': 'Stripe Payment Attempts',
                'db_table': 'core_stripepaymentattempt',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['donation', 'attempt_number'], name='core_stripe_donatio_45376e_idx'), models.Index(fields=['status', '-created_at'], name='core_stripe_status_48b817_idx')],
                'constraints': [models.UniqueConstraint(fields=['donation', 'attempt_number'], name='uniq_attempt_per_donation')],
            },
        ),
    ]
