# Generated by Django 5.2.13 on 2026-04-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_stripepaymentattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepayment',
            name='dispute_reason',
            field=models.CharField(blank=True, default='', help_text='Stripe-reported dispute reason', max_length=100),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='pre_dispute_status',
            field=models.CharField(blank=True, default='', help_text='Status snapshot taken when dispute opened, restored if dispute is won', max_length=30),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed'), ('dispute_lost', 'Dispute Lost')], db_index=True, default='pending', help_text='Payment status', max_length=30),
        ),
    ]
