# Generated by Django 5.2.13 on 2026-04-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_stripepayment_dispute_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepayment',
            name='authentication_link_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the donor was emailed a Stripe Checkout link to complete 3DS / SCA authentication for this payment.', null=True),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='requires_action_url',
            field=models.URLField(blank=True, default='', help_text='Stripe-hosted next_action.use_stripe_sdk URL captured when SCA action is required. Replaced when a Checkout fallback link is issued to the donor.', max_length=2048),
        ),
    ]
