# Generated by Django 5.2.13 on 2026-05-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_stripepayment_authentication_link_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('requires_capture', 'Requires Capture (MOTO auth)'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed'), ('dispute_lost', 'Dispute Lost')], db_index=True, default='pending', help_text='Payment status', max_length=30),
        ),
    ]
