# Generated by Django 5.2.13 on 2026-05-03 00:07
#
# Audit 2026-05-02 §1.4 — Stripe credentials previously sat in plaintext
# inside ``PaymentGatewayConfig.config`` (a ``JSONField``). This migration
# adds three dedicated ``EncryptedCharField`` columns and copies any
# existing values out of the JSON into the encrypted columns. The legacy
# JSON keys are intentionally NOT removed in this migration — they stay
# in place during a one-release dual-write window so that any code path
# still reading the JSON keeps working. A follow-up migration after the
# release purges them.

import encrypted_fields.fields
from django.db import migrations


def copy_creds_into_encrypted_columns(apps, schema_editor):
    """Read each PaymentGatewayConfig row's JSON keys into the encrypted columns."""
    PaymentGatewayConfig = apps.get_model("payments", "PaymentGatewayConfig")

    keys = [
        ("secret_key", "secret_key_encrypted"),
        ("webhook_secret", "webhook_secret_encrypted"),
        ("publishable_key", "publishable_key_encrypted"),
    ]

    for config in PaymentGatewayConfig.objects.all().iterator():
        cfg = config.config or {}
        if not isinstance(cfg, dict):
            continue
        dirty = False
        for json_key, column in keys:
            existing = (cfg.get(json_key) or "").strip()
            if existing and not getattr(config, column):
                setattr(config, column, existing)
                dirty = True
        if dirty:
            config.save(
                update_fields=[
                    "secret_key_encrypted",
                    "webhook_secret_encrypted",
                    "publishable_key_encrypted",
                ]
            )


def clear_encrypted_columns(apps, schema_editor):
    """Reverse migration — clear the new columns (the JSON copy stays intact)."""
    PaymentGatewayConfig = apps.get_model("payments", "PaymentGatewayConfig")
    PaymentGatewayConfig.objects.update(
        secret_key_encrypted=None,
        webhook_secret_encrypted=None,
        publishable_key_encrypted=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_stripepayment_status_for_moto'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='publishable_key_encrypted',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', help_text='Encrypted Stripe publishable key', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='secret_key_encrypted',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', help_text='Encrypted Stripe secret API key', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='webhook_secret_encrypted',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', help_text='Encrypted Stripe webhook signing secret', max_length=255, null=True),
        ),
        migrations.RunPython(
            copy_creds_into_encrypted_columns,
            reverse_code=clear_encrypted_columns,
        ),
    ]
