# Generated by Django 5.2.13 on 2026-04-19 00:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def _repoint_contenttype_forward(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model in ("auditlog", "approvallog", "exportlog"):
        ContentType.objects.filter(app_label="core", model=model).update(
            app_label="audit"
        )


def _repoint_contenttype_reverse(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model in ("auditlog", "approvallog", "exportlog"):
        ContentType.objects.filter(app_label="audit", model=model).update(
            app_label="core"
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0066_remove_audit_state_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ApprovalLog',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('status', models.CharField(max_length=20)),
                        ('comment', models.TextField(blank=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                        ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaign')),
                    ],
                    options={
                        'db_table': 'core_approvallog',
                    },
                ),
                migrations.CreateModel(
                    name='ExportLog',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('export_type', models.CharField(max_length=50)),
                        ('status', models.CharField(max_length=20)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaign')),
                        ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'core_exportlog',
                    },
                ),
                migrations.CreateModel(
                    name='AuditLog',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('READ', 'Read'), ('BULK_CREATE', 'Bulk Create'), ('BULK_UPDATE', 'Bulk Update'), ('BULK_DELETE', 'Bulk Delete'), ('EXPORT', 'Export'), ('IMPORT', 'Import')], db_index=True, help_text='Type of operation performed', max_length=20)),
                        ('model_name', models.CharField(db_index=True, help_text='Model affected by the action', max_length=100)),
                        ('object_id', models.CharField(blank=True, default='', help_text='ID of the affected object', max_length=255)),
                        ('object_repr', models.CharField(blank=True, help_text='String representation of the object', max_length=500)),
                        ('changes', models.JSONField(blank=True, default=dict, help_text='Before and after values for updates')),
                        ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                        ('user_agent', models.TextField(blank=True, help_text='Browser user agent')),
                        ('batch_id', models.CharField(blank=True, db_index=True, default='', help_text='Batch identifier for bulk operations', max_length=255)),
                        ('batch_size', models.PositiveIntegerField(blank=True, help_text='Number of records affected in bulk operation', null=True)),
                        ('summary', models.TextField(blank=True, help_text='Human-readable summary of the action')),
                        ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp of the action')),
                        ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Audit Log',
                        'verbose_name_plural': 'Audit Logs',
                        'db_table': 'core_auditlog',
                        'ordering': ['-created_at'],
                        'indexes': [models.Index(fields=['user', 'created_at'], name='core_auditl_user_id_413764_idx'), models.Index(fields=['model_name', 'action', 'created_at'], name='core_auditl_model_n_44b58e_idx'), models.Index(fields=['batch_id'], name='core_auditl_batch_i_26d9ed_idx'), models.Index(fields=['created_at'], name='core_auditl_created_dc23ea_idx')],
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(
            _repoint_contenttype_forward,
            _repoint_contenttype_reverse,
        ),
    ]
