# Generated by Django 5.2.13 on 2026-05-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_approvallog_campaign_alter_exportlog_campaign'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_user_id_a3c2bc_idx',
            old_name='core_auditl_user_id_413764_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_model_n_790206_idx',
            old_name='core_auditl_model_n_44b58e_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_batch_i_982e87_idx',
            old_name='core_auditl_batch_i_26d9ed_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_created_2c1626_idx',
            old_name='core_auditl_created_dc23ea_idx',
        ),
        migrations.AlterModelTable(
            name='approvallog',
            table=None,
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table=None,
        ),
        migrations.AlterModelTable(
            name='exportlog',
            table=None,
        ),
    ]
