# Generated by Django 5.2.9 on 2026-01-14 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The human-readable name of this device.', max_length=64)),
                ('confirmed', models.BooleanField(default=True, help_text='Is this device ready for use?')),
                ('token', models.CharField(blank=True, max_length=64, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('valid_minutes', models.IntegerField(default=5)),
                ('max_attempts', models.IntegerField(default=3)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(help_text='The user that this device belongs to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email OTP Device',
                'verbose_name_plural': 'Email OTP Devices',
                'db_table': 'otp_emaildevice',
            },
        ),
    ]
