# Generated by Django 5.2.11 on 2026-02-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildevice',
            name='token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
