# Generated by Django 5.2.13 on 2026-04-19 00:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def _repoint_contenttype_forward(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model in ("client", "clientportaluser"):
        ContentType.objects.filter(app_label="core", model=model).update(
            app_label="clients"
        )


def _repoint_contenttype_reverse(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model in ("client", "clientportaluser"):
        ContentType.objects.filter(app_label="clients", model=model).update(
            app_label="core"
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Client',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('name', models.CharField(help_text='Client/Charity name', max_length=255, unique=True)),
                        ('client_code', models.CharField(blank=True, db_index=True, default='', help_text="Short uppercase code for this client (e.g. 'BRC' for British Red Cross). Used as the first folder segment in R2 scan paths: ScanOutput/{client_code}/{appeal_code}/{payment_method}/. Use uppercase letters/digits only, no spaces.", max_length=20)),
                        ('description', models.TextField(blank=True, help_text='About the charity')),
                        ('logo', models.ImageField(blank=True, help_text='Client logo', null=True, upload_to='uploads/client_logos/')),
                        ('email', models.EmailField(blank=True, help_text='Primary contact email', max_length=254)),
                        ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                        ('website', models.URLField(blank=True, help_text='Client website URL')),
                        ('address_line1', models.CharField(blank=True, max_length=255)),
                        ('address_line2', models.CharField(blank=True, max_length=255)),
                        ('city', models.CharField(blank=True, max_length=100)),
                        ('state', models.CharField(blank=True, max_length=100)),
                        ('postal_code', models.CharField(blank=True, max_length=20)),
                        ('country', models.CharField(blank=True, default='', max_length=100)),
                        ('document_ai_processor_id', models.CharField(blank=True, default='', help_text="Google Document AI processor ID for this charity's donation forms. Format: projects/{project}/locations/{location}/processors/{id}. Leave blank if Document AI is not yet configured for this client.", max_length=100)),
                        ('document_ai_location', models.CharField(blank=True, default='eu', help_text="Document AI processor location (e.g. 'eu' or 'us'). Must match the region where the processor was created.", max_length=20)),
                        ('form_field_mapping', models.JSONField(blank=True, default=dict, help_text='JSON mapping of this charity\'s form field labels to canonical extraction field names.  Keys are the verbatim label text from the donation form (lowercased, spaces OK).  Values are canonical field names such as donor_name, donor_first_name, donor_last_name, amount, gift_aid, address_line1, address_line2, city, postcode, phone, email, address_block, contact_consent, email_consent, sms_consent, phone_consent, post_consent.  \n\nExample (raffle form):\n{"full name": "donor_name", "i would like to purchase £": "amount", "i am a uk taxpayer": "gift_aid"}\n\nUniversal NLP types (person, address, phone, email) are detected automatically and do NOT need to be listed here.')),
                        ('is_active', models.BooleanField(default=True, help_text='Is this client active?')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name': 'clients.Client',
                        'verbose_name_plural': 'Clients',
                        'db_table': 'core_client',
                        'ordering': ['name'],
                    },
                ),
                migrations.CreateModel(
                    name='ClientPortalUser',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('role', models.CharField(choices=[('admin', 'Administrator'), ('viewer', 'Viewer'), ('manager', 'Manager')], default='viewer', help_text='User role within the client portal', max_length=20)),
                        ('is_primary', models.BooleanField(default=False, help_text='Primary contact for this client')),
                        ('invited_at', models.DateTimeField(auto_now_add=True)),
                        ('last_login', models.DateTimeField(blank=True, null=True)),
                        ('is_active', models.BooleanField(default=True, help_text='Is this portal user active?')),
                        ('client', models.ForeignKey(help_text='Client organization this user belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='portal_users', to='clients.client')),
                        ('invited_by', models.ForeignKey(blank=True, help_text='Staff user who created this portal user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_portal_users', to=settings.AUTH_USER_MODEL)),
                        ('user', models.OneToOneField(help_text='Django user account', on_delete=django.db.models.deletion.CASCADE, related_name='client_portal_profile', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Client Portal User',
                        'verbose_name_plural': 'Client Portal Users',
                        'db_table': 'core_clientportaluser',
                        'ordering': ['-is_primary', 'user__first_name', 'user__last_name'],
                        'indexes': [models.Index(fields=['client', 'is_active'], name='core_client_client__2d4cf6_idx'), models.Index(fields=['user'], name='core_client_user_id_96eebe_idx')],
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(
            _repoint_contenttype_forward,
            _repoint_contenttype_reverse,
        ),
    ]
