# Generated by Django 5.2.13 on 2026-05-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial_state_only'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientportaluser',
            new_name='clients_cli_client__3fb0cb_idx',
            old_name='core_client_client__2d4cf6_idx',
        ),
        migrations.RenameIndex(
            model_name='clientportaluser',
            new_name='clients_cli_user_id_03afbc_idx',
            old_name='core_client_user_id_96eebe_idx',
        ),
        migrations.AlterModelTable(
            name='client',
            table=None,
        ),
        migrations.AlterModelTable(
            name='clientportaluser',
            table=None,
        ),
    ]
