# Generated by Django 5.2.13 on 2026-04-19 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_add_campaign_models_state_only'),
        ('letters', '0001_initial_state_only'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='letterbatch',
                    name='campaign',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_batches', to='campaigns.campaign'),
                ),
                migrations.AlterField(
                    model_name='lettertemplate',
                    name='campaign',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_templates', to='campaigns.campaign'),
                ),
            ],
            database_operations=[],
        ),
    ]
