# Generated by Django 5.2.13 on 2026-04-21 01:02

from typing import Any

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def deactivate_duplicate_active_templates(
    apps: Any, schema_editor: Any
) -> None:
    """Keep only the most recent active template per (campaign, template_type)."""
    LetterTemplate = apps.get_model("letters", "LetterTemplate")
    seen: set[tuple[str, str]] = set()
    templates = LetterTemplate.objects.filter(is_active=True).order_by(
        "campaign_id", "template_type", "-created_at", "-id"
    )
    to_deactivate: list[int] = []
    for template in templates:
        key = (str(template.campaign_id), template.template_type)
        if key in seen:
            to_deactivate.append(template.id)
        else:
            seen.add(key)
    if to_deactivate:
        LetterTemplate.objects.filter(id__in=to_deactivate).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaigndatafile_datafileupload'),
        ('letters', '0002_alter_letterbatch_campaign_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lettertemplate',
            name='format',
        ),
        migrations.RemoveField(
            model_name='lettertemplate',
            name='placeholder_mapping',
        ),
        migrations.AddField(
            model_name='lettertemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only the active template for each (campaign, type) is used for new letter batches.'),
        ),
        migrations.RunPython(
            deactivate_duplicate_active_templates,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='letterbatch',
            name='failure_template',
            field=models.ForeignKey(blank=True, help_text='Issue template used for rejected donations. If blank, rejected donations are skipped.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_letter_batches', to='letters.lettertemplate'),
        ),
        migrations.AlterField(
            model_name='letterbatch',
            name='regenerate_mode',
            field=models.BooleanField(default=False, help_text='If True, regenerate letters for donations that already have generated letters. If False, only process donations whose letter_status is pending.'),
        ),
        migrations.AlterField(
            model_name='letterbatch',
            name='template',
            field=models.ForeignKey(help_text='Thank-you template used for approved donations in this batch.', on_delete=django.db.models.deletion.CASCADE, related_name='letter_batches', to='letters.lettertemplate'),
        ),
        migrations.AlterField(
            model_name='lettertemplate',
            name='template_type',
            field=models.CharField(choices=[('thank_you', 'Thank You Letter'), ('issue', 'Issue Letter')], db_index=True, default='thank_you', help_text='Thank-you letters go to QA-approved donations; issue letters go to QA-rejected donations.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='lettertemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('campaign', 'template_type'), name='unique_active_template_per_campaign_type'),
        ),
    ]
