# Generated by Django 5.2.13 on 2026-05-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_simplify_letter_template'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='letterbatch',
            new_name='letters_let_campaig_004d17_idx',
            old_name='core_letter_campaig_4b29d9_idx',
        ),
        migrations.RenameIndex(
            model_name='letterbatch',
            new_name='letters_let_status_7a5536_idx',
            old_name='core_letter_status_01f067_idx',
        ),
        migrations.AlterModelTable(
            name='letterbatch',
            table=None,
        ),
        migrations.AlterModelTable(
            name='lettertemplate',
            table=None,
        ),
    ]
