# Generated by Django 5.2.13 on 2026-05-03 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_archived_at_campaign_is_archived'),
        ('letters', '0004_rename_to_default_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterbatch',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='letter_batches', to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='lettertemplate',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='letter_templates', to='campaigns.campaign'),
        ),
    ]
