# Generated by Django 5.2.8 on 2025-12-11 13:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(help_text='Use {{donor_name}}, {{amount}}, etc. for placeholders')),
                ('template_type', models.CharField(choices=[('thank_you', 'Thank You Letter'), ('receipt', 'Receipt'), ('reminder', 'Reminder'), ('followup', 'Follow-up')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
