# Generated by Django 5.2.13 on 2026-04-19 01:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def _repoint_contenttype_forward(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model in ("donation", "donationbatch",):
        ContentType.objects.filter(app_label="core", model=model).update(
            app_label="donations"
        )


def _repoint_contenttype_reverse(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model in ("donation", "donationbatch",):
        ContentType.objects.filter(app_label="donations", model=model).update(
            app_label="core"
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0002_remove_client_state_only'),
        ('campaigns', '0002_campaigndatafile_datafileupload'),
        ('donors', '0002_datafiledonor'),
        ('letters', '0002_alter_letterbatch_campaign_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='DonationBatch',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('batch_name', models.CharField(help_text='Name/identifier for this batch', max_length=255)),
                        ('status', models.CharField(choices=[('pending_qa', 'Pending QA'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending_qa', help_text='QA workflow status for this batch', max_length=20)),
                        ('default_payment_method', models.CharField(default='card', help_text='Default payment method for donations in this batch', max_length=50)),
                        ('default_currency', models.CharField(choices=[('GBP', '£ GBP'), ('USD', '$ USD'), ('EUR', '€ EUR')], default='GBP', help_text='Default currency for donations in this batch (immutable after creation)', max_length=3)),
                        ('reviewed_at', models.DateTimeField(blank=True, help_text='When batch was reviewed', null=True)),
                        ('review_notes', models.TextField(blank=True, default='', help_text='Notes from QA review')),
                        ('total_donations', models.PositiveIntegerField(default=0)),
                        ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount in this batch', max_digits=12)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partially_completed', 'Partially Completed')], db_index=True, default='pending', help_text='Payment processing status for this batch', max_length=30)),
                        ('payment_initiated_at', models.DateTimeField(blank=True, help_text='When payment processing started', null=True)),
                        ('payment_completed_at', models.DateTimeField(blank=True, help_text='When payment processing completed', null=True)),
                        ('successful_payment_count', models.IntegerField(default=0, help_text='Count of successful credit card payments')),
                        ('failed_payment_count', models.IntegerField(default=0, help_text='Count of failed credit card payments')),
                        ('field_data', models.JSONField(blank=True, default=dict, help_text='Flexible metadata and generated artefact paths for this batch')),
                        ('gift_aid_report_path', models.CharField(blank=True, default='', help_text='Media-relative path to the generated HMRC Gift Aid CSV for this batch', max_length=500)),
                        ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_batches', to='campaigns.campaign')),
                        ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
                        ('payment_initiated_by', models.ForeignKey(blank=True, help_text='User who initiated payment processing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_payments_initiated', to=settings.AUTH_USER_MODEL)),
                        ('reviewed_by', models.ForeignKey(blank=True, help_text='User who reviewed/approved the batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_batches', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Donation Batch',
                        'verbose_name_plural': 'Donation Batches',
                        'db_table': 'core_donationbatch',
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='Donation',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('donor_source', models.CharField(choices=[('house_file', 'House File'), ('data_file', 'Data File')], default='house_file', help_text='Source of donor: House File (main) or Data File (campaign-specific)', max_length=20)),
                        ('amount', models.DecimalField(decimal_places=2, help_text='Donation amount', max_digits=12)),
                        ('currency', models.CharField(choices=[('GBP', '£ GBP'), ('USD', '$ USD'), ('EUR', '€ EUR')], default='GBP', help_text='Currency of donation', max_length=3)),
                        ('payment_method', models.CharField(choices=[('card', 'Card'), ('direct_debit', 'Direct Debit'), ('cash', 'Cash'), ('caf', 'CAF Voucher'), ('cheque', 'Cheque'), ('postal_order', 'Postal Order'), ('non_financial', 'Non Financial/No Payment')], default='card', help_text='Payment method used', max_length=30)),
                        ('donation_date', models.DateField(blank=True, help_text='Date of donation', null=True)),
                        ('card_holder_name', models.CharField(blank=True, help_text='Card holder name (for card/direct debit)', max_length=255)),
                        ('card_last_four', models.CharField(blank=True, help_text='Last 4 digits of card number (PCI-DSS compliant — never store full card number)', max_length=4)),
                        ('card_expiry_date', models.CharField(blank=True, help_text='Card expiry date (MM/YYYY format)', max_length=7)),
                        ('direct_debit_start_date', models.DateField(blank=True, help_text='Direct debit start date', null=True)),
                        ('direct_debit_end_date', models.DateField(blank=True, help_text='Direct debit end date', null=True)),
                        ('cheque_number', models.CharField(blank=True, help_text='Cheque number (for cheque payments)', max_length=50)),
                        ('cheque_date', models.DateField(blank=True, help_text='Cheque date (for cheque payments)', null=True)),
                        ('caf_voucher_number', models.CharField(blank=True, help_text='CAF voucher/cheque number', max_length=100)),
                        ('caf_donor_name', models.CharField(blank=True, help_text='CAF donor name (may differ from main donor)', max_length=255)),
                        ('caf_amount', models.DecimalField(blank=True, decimal_places=2, help_text='CAF voucher amount', max_digits=12, null=True)),
                        ('postal_order_number', models.CharField(blank=True, help_text='Postal order/cheque number', max_length=50)),
                        ('postal_order_date', models.DateField(blank=True, help_text='Postal order date', null=True)),
                        ('postal_issuer', models.CharField(blank=True, help_text='Post office or issuer name', max_length=255)),
                        ('non_financial_reason', models.CharField(blank=True, help_text='Reason for non-financial donation (e.g., In-Kind, Volunteering)', max_length=255)),
                        ('non_financial_notes', models.TextField(blank=True, help_text='Additional notes for non-financial donations')),
                        ('gift_aid', models.BooleanField(default=False, help_text='Gift Aid declaration for eligible UK taxpayers')),
                        ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', help_text='Online payment processing status', max_length=20)),
                        ('qa_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], db_index=True, default='pending', help_text='QA review status for this donation', max_length=20)),
                        ('qa_notes', models.TextField(blank=True, default='', help_text='Reviewer notes for donation-level QA actions')),
                        ('letter_status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', help_text='Status of thank-you letter for this donation', max_length=20)),
                        ('letter_generated_at', models.DateTimeField(blank=True, help_text='When the thank-you letter was generated', null=True)),
                        ('donation_frequency', models.CharField(blank=True, choices=[('one_time', 'One Time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], help_text='Donation frequency (optional)', max_length=20)),
                        ('field_data', models.JSONField(blank=True, default=dict, help_text='Custom campaign field values')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='campaigns.campaign')),
                        ('data_file_donor', models.ForeignKey(blank=True, help_text='Matched imported campaign data-file donor source row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donors.datafiledonor')),
                        ('donor', models.ForeignKey(blank=True, help_text='Matched imported house-file donor source row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donors.donor')),
                        ('filled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_donations', to=settings.AUTH_USER_MODEL)),
                        ('letter_batch', models.ForeignKey(blank=True, help_text='Letter batch this donation belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='letters.letterbatch')),
                        ('package_codes', models.ManyToManyField(blank=True, help_text='Package codes associated with this donation', related_name='donations', to='campaigns.packagecode')),
                        ('paying_in_slip', models.ForeignKey(blank=True, help_text='Paying-in slip for bank statement reconciliation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='banking.payinginslip')),
                        ('system_donor', models.ForeignKey(blank=True, help_text='Permanent internal donor profile for donation history', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='donors.systemdonor')),
                        ('batch', models.ForeignKey(help_text='Batch this donation belongs to (required)', on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.donationbatch')),
                    ],
                    options={
                        'db_table': 'core_donation',
                        'ordering': ['-created_at'],
                        'permissions': [('verify_donations', 'Can verify donations')],
                    },
                ),
                migrations.AddIndex(
                    model_name='donationbatch',
                    index=models.Index(fields=['campaign', 'status'], name='batch_campaign_status_idx'),
                ),
                migrations.AddConstraint(
                    model_name='donationbatch',
                    constraint=models.UniqueConstraint(fields=('campaign', 'batch_name'), name='donationbatch_campaign_batch_name_uniq'),
                ),
                migrations.AddIndex(
                    model_name='donation',
                    index=models.Index(fields=['campaign', 'created_at'], name='donation_camp_created_idx'),
                ),
                migrations.AddIndex(
                    model_name='donation',
                    index=models.Index(fields=['campaign', 'donation_date'], name='donation_camp_date_idx'),
                ),
                migrations.AddIndex(
                    model_name='donation',
                    index=models.Index(fields=['payment_method'], name='donation_payment_idx'),
                ),
                migrations.AddIndex(
                    model_name='donation',
                    index=models.Index(fields=['donor'], name='donation_donor_idx'),
                ),
                migrations.AddIndex(
                    model_name='donation',
                    index=models.Index(fields=['data_file_donor'], name='donation_datadonor_idx'),
                ),
                migrations.AddIndex(
                    model_name='donation',
                    index=models.Index(fields=['system_donor'], name='donation_system_donor_idx'),
                ),
                migrations.AddIndex(
                    model_name='donation',
                    index=models.Index(fields=['qa_status'], name='donation_qa_status_idx'),
                ),
                migrations.AddIndex(
                    model_name='donation',
                    index=models.Index(fields=['paying_in_slip', 'qa_status', 'payment_method'], name='donation_banking_idx'),
                ),
                migrations.AddIndex(
                    model_name='donation',
                    index=models.Index(fields=['batch', 'paying_in_slip'], name='donation_batch_slip_idx'),
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(
            _repoint_contenttype_forward,
            _repoint_contenttype_reverse,
        ),
    ]
