# Generated by Django 5.2.13 on 2026-04-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='qa_reject_reason',
            field=models.CharField(blank=True, choices=[('illegible', 'Illegible / cannot read form'), ('no_amount', 'Missing donation amount'), ('no_payment', 'No payment enclosed'), ('amount_mismatch', 'Amount mismatch (form vs payment)'), ('missing_signature', 'Missing signature (Gift Aid)'), ('damaged_form', 'Damaged or incomplete form'), ('duplicate', 'Duplicate submission'), ('cheque_issue', 'Cheque issue (unsigned / post-dated / wrong payee)'), ('missing_donor_details', 'Missing donor details'), ('other', 'Other (see notes)')], default='', help_text="Standardised reject reason shown to donors in failure letters. Required when qa_status == 'rejected'; blank otherwise.", max_length=32),
        ),
    ]
