# Generated by Django 5.2.13 on 2026-04-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_qa_reject_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('dispute_lost', 'Dispute Lost')], db_index=True, default='pending', help_text='Online payment processing status', max_length=20),
        ),
    ]
