# Generated by Django 5.2.13 on 2026-04-25 16:21

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_donation_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='account_number',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', help_text='UK bank account number for direct debits (8 digits, encrypted at rest)', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='sort_code',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', help_text='UK bank sort code for direct debits (6 digits, encrypted at rest)', max_length=6, null=True),
        ),
    ]
