# Generated by Django 5.2.13 on 2026-04-27 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_add_donation_bank_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donationbatch',
            name='reviewer_locked_at',
            field=models.DateTimeField(blank=True, help_text='When the current reviewer claim was acquired or refreshed.', null=True),
        ),
        migrations.AddField(
            model_name='donationbatch',
            name='reviewer_locked_by',
            field=models.ForeignKey(blank=True, help_text='QA reviewer who currently holds this batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_batches', to=settings.AUTH_USER_MODEL),
        ),
    ]
