# Generated by Django 5.2.13 on 2026-04-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_add_donation_bank_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_match_candidates',
            field=models.JSONField(blank=True, default=list, help_text='Borderline donor-match candidate IDs (Jaro-Winkler 0.85-0.95) surfaced for QA reviewer disambiguation.'),
        ),
    ]
