# Generated by Django 5.2.13 on 2026-04-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_add_donation_bank_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='low_confidence_fields',
            field=models.JSONField(blank=True, default=list, help_text='OCR fields whose confidence fell below the campaign threshold. When populated, the donation is excluded from auto-approval and requires explicit reviewer sign-off.'),
        ),
    ]
