# Generated by Django 5.2.13 on 2026-04-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_add_donation_bank_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_reversal_reason',
            field=models.TextField(blank=True, default='', help_text="Reason recorded when banking reversed this donation's payment (cheque bounce, cash discrepancy). Blank otherwise."),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('dispute_lost', 'Dispute Lost'), ('reversed', 'Reversed (Banking)')], db_index=True, default='pending', help_text='Online payment processing status', max_length=20),
        ),
    ]
