# Generated by Django 5.2.13 on 2026-04-27 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaigndatafile_datafileupload'),
        ('donations', '0004_add_donation_bank_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Drop the redundant 2-column index first: the new 3-column index
        # below (campaign, status, created_at) is a strict superset, and
        # Postgres uses the leftmost prefix to satisfy plain
        # (campaign, status) lookups.
        migrations.RemoveIndex(
            model_name='donationbatch',
            name='batch_campaign_status_idx',
        ),
        migrations.AddIndex(
            model_name='donationbatch',
            index=models.Index(fields=['campaign', 'status', 'created_at'], name='batch_camp_stat_created_idx'),
        ),
        migrations.AddIndex(
            model_name='donationbatch',
            index=models.Index(fields=['campaign', 'payment_status'], name='batch_camp_paystat_idx'),
        ),
    ]
