# Generated by Django 5.2.13 on 2026-04-27 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_add_donationbatch_reviewer_lock'),
        ('donations', '0005_donation_low_confidence_fields'),
        ('donations', '0005_donationbatch_batch_camp_stat_created_idx_and_more'),
    ]

    operations = [
    ]
