# Generated by Django 5.2.13 on 2026-04-27 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_donation_donor_match_candidates'),
        ('donations', '0006_merge_20260427_2349'),
    ]

    operations = [
    ]
