# Generated by Django 5.2.13 on 2026-04-27 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_donation_payment_reversal'),
        ('donations', '0007_merge_20260428_0006'),
    ]

    operations = [
    ]
