# Generated by Django 5.2.13 on 2026-04-27 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_alter_donation_payment_status'),
        ('donations', '0008_merge_20260428_0026'),
    ]

    operations = [
    ]
