# Generated by Django 5.2.13 on 2026-04-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_alter_donation_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donor_match_candidates',
            field=models.JSONField(blank=True, default=list, help_text='Borderline donor-match candidates (Jaro-Winkler 0.85-0.95) surfaced for QA reviewer disambiguation. Each entry holds {urn, score, name, system_donor_id}; legacy rows may store a bare PK string list — readers must accept both shapes.'),
        ),
    ]
