# Generated by Django 5.2.13 on 2026-05-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_alter_donation_donor_match_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='letter_void_reason',
            field=models.TextField(blank=True, default='', help_text='Why the issued letter was voided (mirrors payment_reversal_reason on banking-driven voids).'),
        ),
        migrations.AddField(
            model_name='donation',
            name='letter_voided_at',
            field=models.DateTimeField(blank=True, help_text='Set when an already-generated/sent thank-you letter is invalidated by a downstream event (banking reversal, refund). The original letter_status is preserved so history is not lost.', null=True),
        ),
        migrations.AddField(
            model_name='donationbatch',
            name='gift_aid_submitted_at',
            field=models.DateTimeField(blank=True, help_text="Operator marks this when the Gift Aid CSV has been handed to HMRC. Used to gate the 'retraction needed' notification on banking reversal — without this, every gift-aid reversal would warn even when the CSV was never actually submitted, training operators to ignore the alert.", null=True),
        ),
    ]
