# Generated by Django 5.2.13 on 2026-05-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_donation_letter_void_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('requires_capture', 'Requires Capture (MOTO auth)'), ('awaiting_authentication', 'Awaiting Authentication'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('dispute_lost', 'Dispute Lost'), ('reversed', 'Reversed (Banking)')], db_index=True, default='pending', help_text='Online payment processing status', max_length=32),
        ),
    ]
