# Generated by Django 5.2.13 on 2026-05-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0013_add_donation_payment_status_requires_capture'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='donationbatch',
            table=None,
        ),
    ]
