# Generated by Django 5.2.13 on 2026-05-03 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_archived_at_campaign_is_archived'),
        ('donations', '0014_rename_to_default_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='donationbatch',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donation_batches', to='campaigns.campaign'),
        ),
    ]
