# Generated by Django 5.2.13 on 2026-05-03 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_remove_client_state_only'),
        ('campaigns', '0005_campaign_archived_at_campaign_is_archived'),
        ('donations', '0015_alter_donation_campaign_alter_donationbatch_campaign'),
        ('donors', '0005_add_systemdonor_normalized_phone'),
        ('letters', '0005_alter_letterbatch_campaign_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['qa_status', '-created_at'], name='donation_qa_status_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['payment_status', '-created_at'], name='donation_pay_status_ts_idx'),
        ),
    ]
