# Generated by Django 5.2.13 on 2026-04-19 01:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def _repoint_contenttype_forward(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model in ("scanbatch", "scanplaceholder", "scanuploadprogress",):
        ContentType.objects.filter(app_label="core", model=model).update(
            app_label="scans"
        )


def _repoint_contenttype_reverse(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model in ("scanbatch", "scanplaceholder", "scanuploadprogress",):
        ContentType.objects.filter(app_label="scans", model=model).update(
            app_label="core"
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0002_campaigndatafile_datafileupload'),
        ('donations', '0001_initial'),
        ('donors', '0002_datafiledonor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ScanUploadProgress',
                    fields=[
                        ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='scan_progress', serialize=False, to='campaigns.campaign')),
                        ('total_uploaded', models.PositiveIntegerField(default=0)),
                        ('total_expected', models.PositiveIntegerField(default=0, help_text='Expected number of scans (0 = unknown).')),
                        ('latest_urn', models.CharField(blank=True, default='', max_length=255)),
                        ('status', models.CharField(choices=[('idle', 'Idle'), ('scanning', 'Scanning'), ('complete', 'Complete'), ('error', 'Error')], default='idle', max_length=20)),
                        ('last_upload_at', models.DateTimeField(blank=True, null=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'db_table': 'core_scanuploadprogress',
                    },
                ),
                migrations.CreateModel(
                    name='ScanBatch',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('batch_name', models.CharField(help_text='Canonical physical batch identifier derived from the upload filename', max_length=255)),
                        ('source_filename', models.CharField(blank=True, default='', help_text='Original uploaded PDF filename for this physical batch', max_length=255)),
                        ('payment_method', models.CharField(choices=[('card', 'Card'), ('direct_debit', 'Direct Debit'), ('cash', 'Cash'), ('caf', 'CAF Voucher'), ('cheque', 'Cheque'), ('postal_order', 'Postal Order'), ('non_financial', 'Non Financial/No Payment')], help_text='All scans in this batch share this payment method', max_length=30)),
                        ('scan_form_type', models.CharField(choices=[('simplex', 'Simplex'), ('duplex', 'Duplex'), ('simplex_with_payment', 'Simplex + Payment Doc'), ('duplex_with_payment', 'Duplex + Payment Doc'), ('mixed_mail', 'Legacy Mixed Mail / Patch T')], db_index=True, default='simplex', help_text='Physical layout of donor documents in this batch. Simplex/Duplex are valid for card, direct debit, cash, and non-financial batches. Payment-doc layouts are valid for cheque, voucher, and postal order batches.', max_length=30)),
                        ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('partially_completed', 'Partially Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='OCR processing status for this scan batch', max_length=20)),
                        ('total_scans', models.PositiveIntegerField(default=0, help_text='Total number of scans in this batch')),
                        ('processed_scans', models.PositiveIntegerField(default=0, help_text='Number of scans processed by OCR')),
                        ('matched_scans', models.PositiveIntegerField(default=0, help_text='Number of scans matched to a donor')),
                        ('error_message', models.TextField(blank=True, default='', help_text='Error description when this batch failed to process')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_batches', to='campaigns.campaign')),
                        ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scan_batches', to=settings.AUTH_USER_MODEL)),
                        ('donation_batch', models.OneToOneField(blank=True, help_text='Auto-created DonationBatch from OCR results', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_batch', to='donations.donationbatch')),
                    ],
                    options={
                        'verbose_name': 'Scan Batch',
                        'verbose_name_plural': 'Scan Batches',
                        'db_table': 'core_scanbatch',
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='ScanPlaceholder',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('image_url', models.URLField(max_length=1000)),
                        ('image_path', models.CharField(help_text='Path in R2 bucket', max_length=500)),
                        ('urn', models.CharField(blank=True, db_index=True, max_length=50)),
                        ('donor_name', models.CharField(blank=True, max_length=255)),
                        ('is_captured', models.BooleanField(db_index=True, default=False)),
                        ('ocr_data', models.JSONField(blank=True, default=dict, help_text='Raw Document AI results')),
                        ('extracted_data', models.JSONField(blank=True, default=dict, help_text='Structured data extracted from OCR: {"amount": "25.00", "gift_aid": true, "payment_method": "cheque", "donation_date": "15/01/2026", "appeal_code": "...", ...}')),
                        ('ocr_confidence', models.FloatField(default=0.0, help_text='Overall OCR confidence score (0.0-1.0)')),
                        ('ocr_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('matched', 'Matched'), ('unmatched', 'Unmatched')], db_index=True, default='pending', help_text='OCR processing status', max_length=20)),
                        ('processing_error', models.TextField(blank=True)),
                        ('page_keys', models.JSONField(blank=True, default=list, help_text="All R2 keys for this donor's document pages. Empty = single page; populated only for multi-page form types.")),
                        ('original_page_keys', models.JSONField(blank=True, default=list, help_text='Snapshot of R2 keys at ingest (before manual redaction). Used for redaction workflow and audit.')),
                        ('redaction_status', models.CharField(choices=[('pending', 'Pending redaction'), ('in_progress', 'Redaction in progress'), ('completed', 'Redaction completed'), ('blocked', 'Blocked')], db_index=True, default='completed', help_text='Manual redaction state when REQUIRE_MANUAL_REDACTION is enabled', max_length=20)),
                        ('redaction_notes', models.TextField(blank=True, default='', help_text='Optional notes from the staff member who completed redaction')),
                        ('redaction_completed_at', models.DateTimeField(blank=True, help_text='When manual redaction was marked complete', null=True)),
                        ('donor_pdf_key', models.CharField(blank=True, default='', help_text="R2 key for the assembled per-donor PDF (all pages merged into one file). Used by the client portal to serve a viewable copy of the donor's form.", max_length=1000)),
                        ('qr_decoded', models.BooleanField(db_index=True, default=False, help_text='True if a QR code was successfully decoded from the scan image. Warm records always have qr_decoded=True.')),
                        ('qr_raw', models.CharField(blank=True, default='', help_text='Raw QR code string decoded from the scan (appeal_code|package_code|urn).', max_length=500)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholders', to='scans.scanbatch')),
                        ('donation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_placeholder', to='donations.donation')),
                        ('matched_data_file_donor', models.ForeignKey(blank=True, help_text='Data file donor matched via URN lookup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_placeholders', to='donors.datafiledonor')),
                        ('matched_donor', models.ForeignKey(blank=True, help_text='House file donor matched via URN lookup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_placeholders', to='donors.donor')),
                        ('matched_system_donor', models.ForeignKey(blank=True, help_text='Internal donor profile created or resolved for this scan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_placeholders', to='donors.systemdonor')),
                        ('redacted_by', models.ForeignKey(blank=True, help_text='Staff user who uploaded redacted pages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redacted_scan_placeholders', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Scan Placeholder',
                        'verbose_name_plural': 'Scan Placeholders',
                        'db_table': 'core_scanplaceholder',
                        'ordering': ['created_at'],
                        'permissions': [('view_unredacted_scan', 'Can view scan images before manual redaction is complete')],
                    },
                ),
                migrations.AddIndex(
                    model_name='scanbatch',
                    index=models.Index(fields=['campaign', 'status'], name='scanbatch_camp_stat_idx'),
                ),
                migrations.AddConstraint(
                    model_name='scanbatch',
                    constraint=models.UniqueConstraint(fields=('campaign', 'batch_name'), name='scanbatch_campaign_batch_name_uniq'),
                ),
                migrations.AddConstraint(
                    model_name='scanbatch',
                    constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_method__in', ('card', 'direct_debit', 'cash', 'non_financial')), ('scan_form_type__in', ('simplex', 'duplex', 'mixed_mail'))), models.Q(('payment_method__in', ('cheque', 'caf', 'postal_order')), ('scan_form_type__in', ('simplex_with_payment', 'duplex_with_payment', 'mixed_mail'))), _connector='OR'), name='scanbatch_pay_method_form_type_compat'),
                ),
                migrations.AddIndex(
                    model_name='scanplaceholder',
                    index=models.Index(fields=['batch', 'ocr_status'], name='scan_batch_status_idx'),
                ),
                migrations.AddIndex(
                    model_name='scanplaceholder',
                    index=models.Index(fields=['urn', 'is_captured'], name='scan_urn_captured_idx'),
                ),
                migrations.AddIndex(
                    model_name='scanplaceholder',
                    index=models.Index(fields=['redaction_status', '-updated_at'], name='scan_redaction_stat_upd_idx'),
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(
            _repoint_contenttype_forward,
            _repoint_contenttype_reverse,
        ),
    ]
