# Generated by Django 5.2.13 on 2026-04-19 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanuploadprogress',
            options={'verbose_name': 'Scan Upload Progress', 'verbose_name_plural': 'Scan Upload Progress'},
        ),
    ]
