# Generated by Django 5.2.13 on 2026-04-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_alter_scanplaceholder_ocr_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanuploadprogress',
            name='last_error',
            field=models.TextField(blank=True, default='', help_text='Most recent error message reported by the scanner workstation.'),
        ),
    ]
