# Generated by Django 5.2.13 on 2026-04-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0004_scanuploadprogress_last_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanplaceholder',
            name='ocr_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('matched', 'Matched'), ('unmatched', 'Unmatched'), ('skipped', 'Skipped (no Document AI)'), ('needs_rescan', 'Needs rescan')], db_index=True, default='pending', help_text='OCR processing status', max_length=20),
        ),
    ]
