# Generated by Django 5.2.13 on 2026-04-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scans", "0005_alter_scanplaceholder_ocr_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanuploadprogress",
            name="last_completion_dispatched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanuploadprogress",
            name="last_completion_request_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 of the most recent complete-status webhook payload. Used to short-circuit replayed deliveries.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="scanuploadprogress",
            name="last_completion_task_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Celery task id dispatched for the last complete-status webhook.",
                max_length=255,
            ),
        ),
    ]
