# Generated by Django 5.2.13 on 2026-04-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaigndatafile_datafileupload'),
        ('scans', '0006_scanuploadprogress_last_completion_dispatched_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scanuploadprogress',
            index=models.Index(fields=['campaign', 'status'], name='scanprogress_camp_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='scanuploadprogress',
            index=models.Index(fields=['latest_urn'], name='scanprogress_latest_urn_idx'),
        ),
    ]
