# Generated by Django 5.2.13 on 2026-04-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0006_scanuploadprogress_last_completion_dispatched_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanplaceholder',
            name='redaction_error',
            field=models.TextField(blank=True, default='', help_text="Last redaction failure reason. Populated when redaction_status is 'blocked' so QA can see why the upload failed without losing the previous (unredacted) state."),
        ),
    ]
