# Generated by Django 5.2.13 on 2026-04-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0006_scanuploadprogress_last_completion_dispatched_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanbatch',
            name='processed_placeholder_ids',
            field=models.JSONField(blank=True, default=list, help_text='Idempotency keys (ScanPlaceholder UUIDs as strings) for which a progress increment has already been applied. Prevents Celery retries of process_single_scan_task from double-counting the same scan.'),
        ),
    ]
