# Generated by Django 5.2.13 on 2026-04-27 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0007_scanbatch_processed_placeholder_ids'),
        ('scans', '0007_scanuploadprogress_scanprogress_camp_stat_idx_and_more'),
    ]

    operations = [
    ]
