# Generated by Django 5.2.13 on 2026-04-27 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0007_scanplaceholder_redaction_error'),
        ('scans', '0008_merge_20260427_2349'),
    ]

    operations = [
    ]
