# Generated by Django 5.2.13 on 2026-04-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0009_merge_20260428_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanplaceholder',
            name='donor_match_candidates',
            field=models.JSONField(blank=True, default=list, help_text='Borderline donor-match candidates (Jaro-Winkler 0.85-0.95) surfaced for QA reviewer disambiguation. Each entry holds {urn, score, name, system_donor_id}.'),
        ),
    ]
