# Generated by Django 5.2.13 on 2026-05-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0011_redaction_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanplaceholder',
            name='cvv_redacted_at',
            field=models.DateTimeField(blank=True, help_text='When the CVV-only redaction pass was applied to the R2 image. PCI DSS Requirement 3.2 requires CVV/CVC to be redacted on the auth attempt, not after a successful charge — so this fires before redaction_completed_at.', null=True),
        ),
        migrations.AddField(
            model_name='scanplaceholder',
            name='redaction_coords_cvv',
            field=models.JSONField(blank=True, default=list, help_text='Per-page CVV-only blackout rectangles saved by QA. Applied to the R2 image by apply_cvv_redaction_task on every Stripe PaymentIntent.create() return (success or failure). Shape: list of pages, each page a list of {"x", "y", "width", "height"} rect dicts in 0..1 normalised coords.'),
        ),
        migrations.AddField(
            model_name='scanplaceholder',
            name='redaction_coords_post_charge',
            field=models.JSONField(blank=True, default=list, help_text='Per-page post-charge blackout rectangles (PAN, expiry, signature, etc.) saved by QA. Applied to the R2 image by apply_deferred_redaction_task once the charge succeeds, the operator rejects the donation, or the retention TTL expires. Shape matches redaction_coords_cvv.'),
        ),
        migrations.AlterField(
            model_name='scanplaceholder',
            name='redaction_status',
            field=models.CharField(choices=[('pending', 'Pending redaction'), ('in_progress', 'Redaction in progress'), ('cvv_pending', 'Coordinates saved, CVV pass not yet applied'), ('deferred', 'CVV applied, post-charge pass pending'), ('completed', 'Redaction completed'), ('blocked', 'Blocked')], db_index=True, default='completed', help_text='Manual redaction state. RedactionSettings determines which payment methods require redaction before QA approval.', max_length=20),
        ),
    ]
