# Generated by Django 5.2.13 on 2026-05-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0012_scanplaceholder_cvv_redacted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scanbatch',
            table=None,
        ),
        migrations.AlterModelTable(
            name='scanplaceholder',
            table=None,
        ),
        migrations.AlterModelTable(
            name='scanuploadprogress',
            table=None,
        ),
    ]
