"""Audit-signal regression tests for sensitive Donation fields.

The audit pre-/post-save signal handlers in ``audit/signals.py`` snapshot
every field declared on a model and write a stringified diff into
``AuditLog.changes``. ``Donation.sort_code`` and ``Donation.account_number``
are encrypted at rest, but the ORM-level value visible to the signal is
the plaintext — so without the ``audit_exclude_fields`` opt-out, a single
QA edit would persist the cleartext bank PII into the audit log forever.

These tests lock in that behaviour: editing those fields must produce no
``AuditLog.changes`` entry containing either the field name or the value.
"""

from decimal import Decimal

import pytest

from audit.models import AuditLog
from donations.models import Donation
from tests.factories import DonationFactory


@pytest.mark.django_db()
class TestDonationBankFieldAuditExclusion:
    """``audit_exclude_fields`` keeps bank PII out of ``AuditLog.changes``."""

    def test_donation_declares_bank_fields_as_audit_excluded(self) -> None:
        """The model attribute drives the audit signal exclusion."""
        assert "sort_code" in Donation.audit_exclude_fields
        assert "account_number" in Donation.audit_exclude_fields

    def test_updating_sort_code_does_not_leak_into_audit_changes(self) -> None:
        """Editing sort_code on an existing Donation must not write plaintext."""
        donation = DonationFactory(
            payment_method="direct_debit",
            sort_code="111111",
            account_number="22222222",
        )
        # Drop any AuditLog rows generated by factory creation so the test
        # only inspects the post-update audit trail.
        AuditLog.objects.filter(
            model_name="Donation", object_id=str(donation.pk)
        ).delete()

        donation.sort_code = "999999"
        donation.save(update_fields=["sort_code", "updated_at"])

        update_logs = AuditLog.objects.filter(
            model_name="Donation",
            object_id=str(donation.pk),
            action="UPDATE",
        )
        for log in update_logs:
            changes = log.changes or {}
            assert "sort_code" not in changes
            # Neither the previous nor the new plaintext digits should appear
            # anywhere in the serialised diff.
            serialised = str(changes)
            assert "111111" not in serialised
            assert "999999" not in serialised

    def test_updating_account_number_does_not_leak_into_audit_changes(self) -> None:
        """Editing account_number must keep both old and new values opaque."""
        donation = DonationFactory(
            payment_method="direct_debit",
            sort_code="111111",
            account_number="22222222",
        )
        AuditLog.objects.filter(
            model_name="Donation", object_id=str(donation.pk)
        ).delete()

        donation.account_number = "87654321"
        donation.save(update_fields=["account_number", "updated_at"])

        update_logs = AuditLog.objects.filter(
            model_name="Donation",
            object_id=str(donation.pk),
            action="UPDATE",
        )
        for log in update_logs:
            changes = log.changes or {}
            assert "account_number" not in changes
            serialised = str(changes)
            assert "22222222" not in serialised
            assert "87654321" not in serialised

    def test_other_field_changes_still_audit_normally(self) -> None:
        """Non-excluded field edits keep producing audit diffs as before."""
        donation = DonationFactory(
            payment_method="direct_debit",
            sort_code="111111",
            account_number="22222222",
            amount=Decimal("10.00"),
        )
        AuditLog.objects.filter(
            model_name="Donation", object_id=str(donation.pk)
        ).delete()

        donation.amount = Decimal("25.00")
        donation.save(update_fields=["amount", "updated_at"])

        update_logs = AuditLog.objects.filter(
            model_name="Donation",
            object_id=str(donation.pk),
            action="UPDATE",
        )
        amount_logs = [log for log in update_logs if "amount" in (log.changes or {})]
        assert amount_logs, "amount edits should still generate an audit row"
        amount_change = amount_logs[0].changes["amount"]
        assert amount_change["old"] == "10.00"
        assert amount_change["new"] == "25.00"
