# Generated by Django 5.2.13 on 2026-04-19 00:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def _repoint_contenttype_forward(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model in ("campaign", "campaignfield", "packagecode"):
        ContentType.objects.filter(app_label="core", model=model).update(
            app_label="campaigns"
        )


def _repoint_contenttype_reverse(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model in ("campaign", "campaignfield", "packagecode"):
        ContentType.objects.filter(app_label="campaigns", model=model).update(
            app_label="core"
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial_state_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='PackageCode',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('code', models.CharField(db_index=True, help_text='Unique package code', max_length=100, unique=True)),
                        ('description', models.CharField(blank=True, help_text='Optional description of the package', max_length=255)),
                        ('is_active', models.BooleanField(default=True, help_text='Is this package code active?')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name': 'Package Code',
                        'verbose_name_plural': 'Package Codes',
                        'db_table': 'core_packagecode',
                        'ordering': ['code'],
                    },
                ),
                migrations.CreateModel(
                    name='Campaign',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('name', models.CharField(max_length=255)),
                        ('description', models.TextField(blank=True)),
                        ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                        ('allow_multiple_submissions', models.BooleanField(default=True)),
                        ('require_authentication', models.BooleanField(default=False)),
                        ('appeal_code', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                        ('package_code', models.CharField(blank=True, default='', max_length=100)),
                        ('appeal_type', models.CharField(choices=[('Donation', 'Donation'), ('Raffle', 'Raffle')], default='Donation', max_length=32)),
                        ('appeal_start', models.DateField(default=django.utils.timezone.now)),
                        ('appeal_end', models.DateField(default=django.utils.timezone.now)),
                        ('hgv_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='High Gift Value threshold', max_digits=10)),
                        ('lgv_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Low Gift Value threshold', max_digits=10)),
                        ('campaign_manager_emails', models.TextField(blank=True, default='', help_text='Comma-separated list of email addresses to notify for HGV donations')),
                        ('donor_source', models.CharField(choices=[('house_file', 'House File'), ('data_file', 'Data File')], default='house_file', help_text='Donor lookup source: House File (global donors) or Data File (campaign-specific donors)', max_length=20)),
                        ('campaign_temperature', models.CharField(choices=[('warm', 'Warm'), ('cold', 'Cold')], db_index=True, default='cold', help_text='Campaign type: Warm campaigns target known supporters and expect QR-backed forms whose donors already exist in the configured source. Cold campaigns handle handwritten or new-supporter forms where QR is not expected and new donor creation is allowed.', max_length=20)),
                        ('scan_purpose', models.CharField(choices=[('donation', 'Donation — create donation records'), ('donor_update', 'Donor Update — update donor details only (no payment)')], db_index=True, default='donation', help_text="What to do with scanned data: 'donation' creates donation records; 'donor_update' updates donor contact details and creates a non-financial donation as an audit trail.", max_length=20)),
                        ('start_date', models.DateField(blank=True, null=True)),
                        ('end_date', models.DateField(blank=True, null=True)),
                        ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('payment_eligible', models.BooleanField(db_index=True, default=False, help_text='Campaign is eligible for payment processing (all batches QA approved)')),
                        ('payment_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('partially_completed', 'Partially Completed'), ('failed', 'Failed')], db_index=True, default='not_started', help_text='Overall payment status for campaign', max_length=30)),
                        ('payment_processed_at', models.DateTimeField(blank=True, help_text='When payment processing was completed', null=True)),
                        ('total_payment_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount of credit card payments in campaign', max_digits=12)),
                        ('successful_payments', models.IntegerField(default=0, help_text='Count of successful payments')),
                        ('failed_payments', models.IntegerField(default=0, help_text='Count of failed payments')),
                        ('client', models.ForeignKey(help_text='Client/charity this campaign belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='clients.client')),
                        ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                        ('payment_processed_by', models.ForeignKey(blank=True, help_text='User who processed campaign payments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_campaigns', to=settings.AUTH_USER_MODEL)),
                        ('package_codes', models.ManyToManyField(related_name='campaigns', to='campaigns.packagecode')),
                    ],
                    options={
                        'db_table': 'campaigns',
                        'ordering': ['-created_at'],
                        'permissions': [('manage_campaigns', 'Can manage campaigns (create/edit forms)'), ('fill_donations', 'Can fill donation forms')],
                    },
                ),
                migrations.CreateModel(
                    name='CampaignField',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('label', models.CharField(help_text="Field label (e.g., 'Donor Name')", max_length=255)),
                        ('field_type', models.CharField(choices=[('text', 'Text Input'), ('number', 'Number Input'), ('email', 'Email Input'), ('phone', 'Phone Input'), ('date', 'Date Input'), ('dropdown', 'Dropdown Select'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkboxes'), ('textarea', 'Text Area'), ('file', 'File Upload')], default='text', max_length=20)),
                        ('placeholder', models.CharField(blank=True, max_length=255)),
                        ('help_text', models.CharField(blank=True, max_length=500)),
                        ('required', models.BooleanField(default=False)),
                        ('is_default_field', models.BooleanField(default=False, help_text='Default field that cannot be deleted')),
                        ('options', models.JSONField(blank=True, default=list, help_text='Options for dropdown/radio/checkbox')),
                        ('order', models.PositiveIntegerField(default=0)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='campaigns.campaign')),
                    ],
                    options={
                        'db_table': 'core_campaignfield',
                        'ordering': ['order', 'created_at'],
                        'constraints': [models.UniqueConstraint(fields=('campaign', 'label'), name='unique_campaign_field_label')],
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(
            _repoint_contenttype_forward,
            _repoint_contenttype_reverse,
        ),
    ]
