# Generated by Django 5.2.13 on 2026-04-19 00:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def _repoint_contenttype_forward(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model in ("campaigndatafile", "datafileupload",):
        ContentType.objects.filter(app_label="core", model=model).update(
            app_label="campaigns"
        )


def _repoint_contenttype_reverse(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model in ("campaigndatafile", "datafileupload",):
        ContentType.objects.filter(app_label="campaigns", model=model).update(
            app_label="core"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_add_campaign_models_state_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CampaignDataFile',
                    fields=[
                        ('campaign', models.OneToOneField(help_text='Campaign this data file belongs to', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='data_file', serialize=False, to='campaigns.campaign')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('total_donors', models.PositiveIntegerField(default=0, help_text='Total number of donors in this data file')),
                        ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_data_files', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Campaign Data File',
                        'verbose_name_plural': 'Campaign Data Files',
                        'db_table': 'core_campaigndatafile',
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='DataFileUpload',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('file', models.FileField(help_text='CSV/Excel file with donor data', upload_to='uploads/datafile_donors/')),
                        ('total_rows', models.PositiveIntegerField(default=0, help_text='Total rows in file')),
                        ('successful_imports', models.PositiveIntegerField(default=0, help_text='Successfully imported')),
                        ('failed_imports', models.PositiveIntegerField(default=0, help_text='Failed imports')),
                        ('error_log', models.JSONField(blank=True, default=list, help_text='List of errors encountered during import')),
                        ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('completed_at', models.DateTimeField(blank=True, null=True)),
                        ('data_file', models.ForeignKey(help_text='Data file this upload belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='campaigns.campaigndatafile')),
                        ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datafile_uploads', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Data File Upload',
                        'verbose_name_plural': 'Data File Uploads',
                        'db_table': 'core_datafileupload',
                        'ordering': ['-created_at'],
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(
            _repoint_contenttype_forward,
            _repoint_contenttype_reverse,
        ),
    ]
