# Generated by Django 5.2.13 on 2026-04-27 21:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaigndatafile_datafileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ocr_confidence_threshold',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.700'), help_text='Per-field OCR confidence floor (0.000-1.000). Donations whose amount or date confidence falls below this threshold are flagged for mandatory QA review and cannot be auto-approved on batch approval. Default is 0.700.', max_digits=4),
        ),
    ]
