# Generated by Django 5.2.13 on 2026-05-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_ocr_confidence_threshold'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='campaign',
            table=None,
        ),
        migrations.AlterModelTable(
            name='campaigndatafile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='campaignfield',
            table=None,
        ),
        migrations.AlterModelTable(
            name='datafileupload',
            table=None,
        ),
        migrations.AlterModelTable(
            name='packagecode',
            table=None,
        ),
    ]
