# Generated by Django 5.2.13 on 2026-05-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_rename_to_default_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When the campaign was archived.', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Archived campaigns are hidden from active lists and cannot accept new donations.'),
        ),
    ]
