# Generated by Django 5.2.13 on 2026-05-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial_state_only'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_05b4bc_idx',
            old_name='core_notifi_user_id_1cc5b6_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_f2ad08_idx',
            old_name='core_notifi_user_id_f286cd_idx',
        ),
        migrations.AlterModelTable(
            name='notification',
            table=None,
        ),
    ]
