# Generated by Django 5.2.13 on 2026-04-19 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial_state_only'),
        ('clients', '0001_initial_state_only'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='payinginslip',
                    name='client',
                    field=models.ForeignKey(blank=True, help_text='Primary client (nullable for multi-client slips)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paying_in_slips', to='clients.client'),
                ),
            ],
            database_operations=[],
        ),
    ]
