# Generated by Django 5.2.13 on 2026-05-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_remove_client_state_only'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payinginslip',
            new_name='banking_pay_client__52576d_idx',
            old_name='core_paying_client__638e8c_idx',
        ),
        migrations.RenameIndex(
            model_name='payinginslip',
            new_name='banking_pay_status_06b7d4_idx',
            old_name='core_paying_status_2f8864_idx',
        ),
        migrations.AlterModelTable(
            name='payinginslip',
            table=None,
        ),
    ]
