"""Views for custom admin module."""

from audit.admin_views import audit_log_history
from banking.admin_views import (
    create_paying_in_slip,
    daily_banking_batch_detail,
    daily_banking_dashboard,
)
from banking.admin_views_htmx import (
    htmx_banking_batch_queue,
)
from banking.admin_views_slips import (
    slip_add_donations,
    slip_delete,
    slip_detail,
    slip_edit,
    slip_list,
    slip_print,
    slip_record_processing,
    slip_remove_donation,
    slip_update_status,
)
from campaigns.admin_views import (
    admin_campaigns,
    campaign_create,
    campaign_edit,
    download_campaign_import_sample,
)
from clients.admin_views import (
    client_create,
    client_edit,
    client_payment_config,
    client_setup,
    portal_user_create,
)
from donations.admin_views import (
    donation_edit,
)
from donations.admin_views_batches import (
    donation_batch_detail,
    donation_batch_list,
)
from donations.admin_views_quick_edit import donation_quick_edit
from donations.phone_intake_views import (
    phone_intake_charge,
    phone_intake_console,
    phone_intake_create_donation,
    phone_intake_create_system_donor,
    phone_intake_help,
    phone_intake_refund,
)
from donors.admin_views_imports import donor_imports
from donors.admin_views_supporters import (
    htmx_supporter_donations,
    supporter_detail,
    supporter_list,
)
from invoices.admin_views import (
    invoice_change_status,
    invoice_create_with_services,
    invoice_detail,
    invoice_generate_pdf,
    invoice_list,
    invoice_mark_paid,
    invoice_metrics_api,
    invoice_preview_pdf,
    invoice_send_email_view,
)
from invoices.admin_views_edit import (
    invoice_edit,
    invoice_update_line_items,
)
from invoices.admin_views_settings import (
    service_category_create,
    service_category_update,
    service_item_create,
    service_item_delete,
    service_item_update,
    service_items_api,
    service_settings,
)
from letters.admin_views import (
    add_letter_template,
    cancel_batch,
    download_batch_file,
    download_letter,
    generate_letter,
    letter_batch_detail,
    letter_batch_status_api,
    letter_batches,
    letter_print_console,
    letter_setup_campaign,
    letter_task_status,
    preview_active_template,
    reset_failed_letters,
    serve_reference_guide,
    view_generated_letters,
)
from notifications.admin_views import (
    notification_count_api,
    notification_list,
    notification_mark_all_read,
    notification_mark_read,
    notification_stream_api,
)
from scans.admin_views import (
    scan_batch_detail_view,
    scan_new_batch_view,
    scan_processing_dashboard,
    scan_redacted_pages_upload,
)
from scans.admin_views_batch import (
    donation_batch_delete,
)

from .dashboard import admin_dashboard, admin_settings
from .qa_review import (
    download_gift_aid_report,
    htmx_assign_donor_to_donation,
    mark_gift_aid_submitted,
    qa_approve_batch,
    qa_batch_resubmit,
    qa_batch_review,
    qa_batch_stats_api,
    qa_dashboard,
    qa_reject_batch,
    qa_resolve_pending_donor,
    qa_save_scan_redaction,
    qa_send_authentication_link,
    qa_single_donation_review,
    qa_update_batch_status,
)
from .reports import (
    admin_reports,
    admin_reports_filter_partial,
    admin_reports_results_partial,
    report_export,
    report_export_pdf,
    report_scans_zip,
)
from .users import admin_user_management

__all__ = [
    "add_letter_template",
    "admin_campaigns",
    "admin_dashboard",
    "admin_reports",
    "admin_reports_filter_partial",
    "admin_reports_results_partial",
    "admin_settings",
    "admin_user_management",
    "audit_log_history",
    "campaign_create",
    "campaign_edit",
    "cancel_batch",
    "client_create",
    "client_edit",
    "client_payment_config",
    "client_setup",
    "create_paying_in_slip",
    "daily_banking_batch_detail",
    "daily_banking_dashboard",
    "donation_batch_delete",
    "donation_batch_detail",
    "donation_batch_list",
    "donation_edit",
    "donation_quick_edit",
    "donor_imports",
    "download_batch_file",
    "download_campaign_import_sample",
    "download_gift_aid_report",
    "download_letter",
    "generate_letter",
    "htmx_assign_donor_to_donation",
    "htmx_banking_batch_queue",
    "htmx_supporter_donations",
    "invoice_change_status",
    "invoice_create_with_services",
    "invoice_detail",
    "invoice_edit",
    "invoice_generate_pdf",
    "invoice_list",
    "invoice_mark_paid",
    "invoice_metrics_api",
    "invoice_preview_pdf",
    "invoice_send_email_view",
    "invoice_update_line_items",
    "letter_batch_detail",
    "letter_batch_status_api",
    "letter_batches",
    "letter_print_console",
    "letter_setup_campaign",
    "letter_task_status",
    "mark_gift_aid_submitted",
    "notification_count_api",
    "notification_list",
    "notification_mark_all_read",
    "notification_mark_read",
    "notification_stream_api",
    "phone_intake_charge",
    "phone_intake_console",
    "phone_intake_create_donation",
    "phone_intake_create_system_donor",
    "phone_intake_help",
    "phone_intake_refund",
    "portal_user_create",
    "preview_active_template",
    "qa_approve_batch",
    "qa_batch_resubmit",
    "qa_batch_review",
    "qa_batch_stats_api",
    "qa_dashboard",
    "qa_reject_batch",
    "qa_resolve_pending_donor",
    "qa_save_scan_redaction",
    "qa_send_authentication_link",
    "qa_single_donation_review",
    "qa_update_batch_status",
    "report_export",
    "report_export_pdf",
    "report_scans_zip",
    "reset_failed_letters",
    "scan_batch_detail_view",
    "scan_new_batch_view",
    "scan_processing_dashboard",
    "scan_redacted_pages_upload",
    "serve_reference_guide",
    "service_category_create",
    "service_category_update",
    "service_item_create",
    "service_item_delete",
    "service_item_update",
    "service_items_api",
    "service_settings",
    "slip_add_donations",
    "slip_delete",
    "slip_detail",
    "slip_edit",
    "slip_list",
    "slip_print",
    "slip_record_processing",
    "slip_remove_donation",
    "slip_update_status",
    "supporter_detail",
    "supporter_list",
    "view_generated_letters",
]
