# Generated by Django 5.2.13 on 2026-04-19 00:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def _repoint_contenttype_forward(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model in ("donor", "donorupload", "segment", "systemdonor"):
        ContentType.objects.filter(app_label="core", model=model).update(
            app_label="donors"
        )


def _repoint_contenttype_reverse(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model in ("donor", "donorupload", "segment", "systemdonor"):
        ContentType.objects.filter(app_label="donors", model=model).update(
            app_label="core"
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_add_campaign_models_state_only'),
        ('clients', '0001_initial_state_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='DonorUpload',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('file', models.FileField(upload_to='uploads/donors/')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                        ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'core_donorupload',
                    },
                ),
                migrations.CreateModel(
                    name='Segment',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('name', models.CharField(max_length=255)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                    ],
                    options={
                        'db_table': 'core_segment',
                    },
                ),
                migrations.CreateModel(
                    name='Donor',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='System-generated unique identifier for the donor', primary_key=True, serialize=False)),
                        ('urn', models.CharField(blank=True, help_text='Unique Reference Number from the charity. Null for new donors captured before the charity assigns a URN.', max_length=50, null=True)),
                        ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Rev', 'Rev'), ('Sir', 'Sir'), ('Lady', 'Lady'), ('Other', 'Other')], max_length=10)),
                        ('first_name', models.CharField(max_length=100)),
                        ('last_name', models.CharField(max_length=100)),
                        ('email', models.EmailField(blank=True, help_text='Email address', max_length=254)),
                        ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20)),
                        ('address_line1', models.CharField(blank=True, help_text='Address Line 1', max_length=255)),
                        ('address_line2', models.CharField(blank=True, help_text='Address Line 2', max_length=255)),
                        ('city', models.CharField(blank=True, max_length=100)),
                        ('county', models.CharField(blank=True, max_length=100)),
                        ('postcode', models.CharField(blank=True, help_text='UK Postcode', max_length=20)),
                        ('country', models.CharField(default='United Kingdom', max_length=100)),
                        ('date_of_birth', models.DateField(blank=True, help_text='Date of birth', null=True)),
                        ('age', models.PositiveIntegerField(blank=True, help_text='Age (if DOB not provided)', null=True)),
                        ('gift_aid_declaration', models.BooleanField(default=False, help_text='Whether the donor has made a Gift Aid declaration')),
                        ('gift_aid_date', models.DateField(blank=True, help_text='Date the donor made their Gift Aid declaration', null=True)),
                        ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('pending_export', 'Pending Export')], default='verified', help_text='Verified: confirmed donor in the house file. Unverified: newly created during data-file campaign entry, not yet confirmed. Pending Export: created during cold campaign entry for a donor not in the house file — reference to be exported to the charity.', max_length=20)),
                        ('contact_status', models.CharField(choices=[('normal', 'Normal'), ('gone_away', 'Gone Away'), ('deceased', 'Deceased'), ('bad_address', 'Bad Address'), ('temporarily_suppressed', 'Temporarily Suppressed')], default='normal', help_text='Operational contactability status for donor servicing and postal suppression.', max_length=30)),
                        ('contact_status_reason', models.CharField(blank=True, help_text="Reason or source for the donor's current contact status", max_length=255)),
                        ('contact_status_changed_at', models.DateTimeField(blank=True, help_text="When the donor's current contact status was last changed", null=True)),
                        ('address_last_verified_at', models.DateTimeField(blank=True, help_text='When the donor address was last confirmed or corrected', null=True)),
                        ('consent_contact', models.BooleanField(default=False, help_text='Consents to being contacted by charity')),
                        ('opt_in_email', models.BooleanField(default=False, help_text='Opt-in for email contact')),
                        ('opt_in_sms', models.BooleanField(default=False, help_text='Opt-in for SMS contact')),
                        ('opt_in_phone', models.BooleanField(default=False, help_text='Opt-in for phone contact')),
                        ('opt_in_post', models.BooleanField(default=False, help_text='Opt-in for postal contact')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('client', models.ForeignKey(blank=True, help_text='Client/charity this donor belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='clients.client')),
                        ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donors_created', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'donors.Donor',
                        'verbose_name_plural': 'Donors',
                        'db_table': 'core_donor',
                        'ordering': ['last_name', 'first_name'],
                        'indexes': [models.Index(fields=['client', 'urn'], name='core_donor_client__571817_idx'), models.Index(fields=['urn'], name='core_donor_urn_82d02a_idx'), models.Index(fields=['last_name', 'first_name'], name='core_donor_last_na_f38a81_idx'), models.Index(fields=['email'], name='core_donor_email_e54a71_idx'), models.Index(fields=['postcode'], name='core_donor_postcod_32e474_idx'), models.Index(fields=['verification_status'], name='core_donor_verific_a98710_idx'), models.Index(fields=['contact_status'], name='core_donor_contact_90bc85_idx')],
                        'constraints': [models.UniqueConstraint(fields=('client', 'urn'), name='unique_donor_urn_per_client')],
                    },
                ),
                migrations.CreateModel(
                    name='SystemDonor',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='System-generated unique identifier for the internal donor profile', primary_key=True, serialize=False)),
                        ('external_urn', models.CharField(blank=True, default='', help_text='Latest known source-system URN for this donor, when available', max_length=50)),
                        ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Rev', 'Rev'), ('Sir', 'Sir'), ('Lady', 'Lady'), ('Other', 'Other')], max_length=10)),
                        ('first_name', models.CharField(help_text='Donor first name', max_length=100)),
                        ('last_name', models.CharField(help_text='Donor last name', max_length=100)),
                        ('email', models.EmailField(blank=True, help_text='Email address', max_length=254)),
                        ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20)),
                        ('address_line1', models.CharField(blank=True, help_text='Address Line 1', max_length=255)),
                        ('address_line2', models.CharField(blank=True, help_text='Address Line 2', max_length=255)),
                        ('city', models.CharField(blank=True, help_text='City', max_length=100)),
                        ('county', models.CharField(blank=True, help_text='County', max_length=100)),
                        ('postcode', models.CharField(blank=True, help_text='UK Postcode', max_length=20)),
                        ('country', models.CharField(default='United Kingdom', help_text='Country', max_length=100)),
                        ('date_of_birth', models.DateField(blank=True, help_text='Date of birth', null=True)),
                        ('age', models.PositiveIntegerField(blank=True, help_text='Age (if date of birth is not available)', null=True)),
                        ('gift_aid_declaration', models.BooleanField(default=False, help_text='Whether the donor has made a Gift Aid declaration')),
                        ('gift_aid_date', models.DateField(blank=True, help_text='Date the donor made their Gift Aid declaration', null=True)),
                        ('contact_status', models.CharField(choices=[('normal', 'Normal'), ('gone_away', 'Gone Away'), ('deceased', 'Deceased'), ('bad_address', 'Bad Address'), ('temporarily_suppressed', 'Temporarily Suppressed')], default='normal', help_text='Operational contactability status for donor servicing', max_length=30)),
                        ('contact_status_reason', models.CharField(blank=True, help_text="Reason or source for the donor's current contact status", max_length=255)),
                        ('contact_status_changed_at', models.DateTimeField(blank=True, help_text="When the donor's current contact status was last changed", null=True)),
                        ('address_last_verified_at', models.DateTimeField(blank=True, help_text='When the donor address was last confirmed or corrected', null=True)),
                        ('consent_contact', models.BooleanField(default=False, help_text='Consents to being contacted by charity')),
                        ('opt_in_email', models.BooleanField(default=False, help_text='Opt-in for email contact')),
                        ('opt_in_sms', models.BooleanField(default=False, help_text='Opt-in for SMS contact')),
                        ('opt_in_phone', models.BooleanField(default=False, help_text='Opt-in for phone contact')),
                        ('opt_in_post', models.BooleanField(default=False, help_text='Opt-in for postal contact')),
                        ('source_snapshot', models.JSONField(blank=True, default=dict, help_text='Latest imported or OCR-derived donor snapshot used for upsert')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('client', models.ForeignKey(blank=True, help_text='Client/charity this internal donor belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_donors', to='clients.client')),
                        ('created_by', models.ForeignKey(help_text='User who first created this internal donor profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_donors_created', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'System Donor',
                        'verbose_name_plural': 'System Donors',
                        'db_table': 'core_systemdonor',
                        'ordering': ['last_name', 'first_name'],
                        'indexes': [models.Index(fields=['client', 'external_urn'], name='core_system_client__f6a3bf_idx'), models.Index(fields=['client', 'last_name', 'first_name'], name='core_system_client__82a10f_idx'), models.Index(fields=['email'], name='core_system_email_9b871c_idx'), models.Index(fields=['phone'], name='core_system_phone_77d3f7_idx'), models.Index(fields=['postcode'], name='core_system_postcod_2bbc9a_idx'), models.Index(fields=['contact_status'], name='core_system_contact_1835eb_idx')],
                        'constraints': [models.UniqueConstraint(fields=('client', 'external_urn'), name='unique_system_donor_external_urn_per_client')],
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(
            _repoint_contenttype_forward,
            _repoint_contenttype_reverse,
        ),
    ]
