# Generated by Django 5.2.13 on 2026-04-19 00:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def _repoint_contenttype_forward(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model in ("datafiledonor",):
        ContentType.objects.filter(app_label="core", model=model).update(
            app_label="donors"
        )


def _repoint_contenttype_reverse(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model in ("datafiledonor",):
        ContentType.objects.filter(app_label="donors", model=model).update(
            app_label="core"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaigndatafile_datafileupload'),
        ('clients', '0001_initial_state_only'),
        ('donors', '0001_initial_state_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='DataFileDonor',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('urn', models.CharField(help_text='Unique Reference Number for the donor in this campaign', max_length=50)),
                        ('package_code', models.CharField(blank=True, help_text='Package code assigned to the donor for this campaign', max_length=100)),
                        ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Rev', 'Rev'), ('Sir', 'Sir'), ('Lady', 'Lady'), ('Other', 'Other')], max_length=10)),
                        ('first_name', models.CharField(max_length=100)),
                        ('last_name', models.CharField(max_length=100)),
                        ('email', models.EmailField(blank=True, max_length=254)),
                        ('phone', models.CharField(blank=True, max_length=20)),
                        ('address_line1', models.CharField(blank=True, max_length=255)),
                        ('address_line2', models.CharField(blank=True, max_length=255)),
                        ('city', models.CharField(blank=True, max_length=100)),
                        ('county', models.CharField(blank=True, max_length=100)),
                        ('postcode', models.CharField(blank=True, max_length=20)),
                        ('country', models.CharField(default='United Kingdom', max_length=100)),
                        ('date_of_birth', models.DateField(blank=True, null=True)),
                        ('age', models.PositiveIntegerField(blank=True, null=True)),
                        ('gift_aid_declaration', models.BooleanField(default=False, help_text='Whether the donor has made a Gift Aid declaration')),
                        ('gift_aid_date', models.DateField(blank=True, help_text='Date the donor made their Gift Aid declaration', null=True)),
                        ('contact_status', models.CharField(choices=[('normal', 'Normal'), ('gone_away', 'Gone Away'), ('deceased', 'Deceased'), ('bad_address', 'Bad Address'), ('temporarily_suppressed', 'Temporarily Suppressed')], default='normal', help_text='Operational contactability status for donor servicing and postal suppression.', max_length=30)),
                        ('contact_status_reason', models.CharField(blank=True, help_text="Reason or source for the donor's current contact status", max_length=255)),
                        ('contact_status_changed_at', models.DateTimeField(blank=True, help_text="When the donor's current contact status was last changed", null=True)),
                        ('address_last_verified_at', models.DateTimeField(blank=True, help_text='When the donor address was last confirmed or corrected', null=True)),
                        ('consent_contact', models.BooleanField(default=False)),
                        ('no_thank_you', models.BooleanField(default=False, help_text='Donor has opted out of thank-you communications.')),
                        ('opt_in_email', models.BooleanField(default=False)),
                        ('opt_in_sms', models.BooleanField(default=False)),
                        ('opt_in_phone', models.BooleanField(default=False)),
                        ('opt_in_post', models.BooleanField(default=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('client', models.ForeignKey(blank=True, help_text='Client/charity this donor belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_file_donors', to='clients.client')),
                        ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datafile_donors_created', to=settings.AUTH_USER_MODEL)),
                        ('data_file', models.ForeignKey(help_text='Data file this donor belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='campaigns.campaigndatafile')),
                        ('house_file_donor', models.ForeignKey(blank=True, help_text='Link to house file donor if exists', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_file_entries', to='donors.donor')),
                    ],
                    options={
                        'verbose_name': 'Data File Donor',
                        'verbose_name_plural': 'Data File Donors',
                        'db_table': 'core_datafiledonor',
                        'ordering': ['last_name', 'first_name'],
                        'indexes': [models.Index(fields=['client', 'urn'], name='core_datafi_client__9ad37f_idx'), models.Index(fields=['data_file', 'urn'], name='core_datafi_data_fi_c87196_idx'), models.Index(fields=['package_code'], name='core_datafi_package_c28584_idx'), models.Index(fields=['last_name', 'first_name'], name='core_datafi_last_na_b7331d_idx'), models.Index(fields=['email'], name='core_datafi_email_9b1866_idx'), models.Index(fields=['postcode'], name='core_datafi_postcod_cccbc0_idx'), models.Index(fields=['contact_status'], name='core_datafi_contact_50dd24_idx')],
                        'constraints': [models.UniqueConstraint(fields=('data_file', 'urn'), name='unique_urn_per_datafile')],
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(
            _repoint_contenttype_forward,
            _repoint_contenttype_reverse,
        ),
    ]
