# Generated by Django 5.2.13 on 2026-04-25 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial_state_only'),
        ('donors', '0002_datafiledonor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemdonor',
            name='pending_review',
            field=models.BooleanField(default=False, help_text='True when the donor was auto-created by scan pipeline and not yet confirmed by QA.'),
        ),
        migrations.AddIndex(
            model_name='systemdonor',
            index=models.Index(fields=['pending_review'], name='core_system_pending_07c0b0_idx'),
        ),
    ]
