# Generated by Django 5.2.13 on 2026-04-27 22:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial_state_only'),
        ('donors', '0003_systemdonor_pending_review_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='systemdonor',
            index=models.Index(fields=['client', 'postcode'], name='core_system_client__694633_idx'),
        ),
    ]
