# Generated by Django 5.2.13 on 2026-05-03 11:53
#
# Hardened 2026-05-05: 5 of the 7 ``donor`` indexes have short names in
# production (``core_donor_urn_idx``, ``core_donor_name_idx``, …) because
# ``core/0027_donor_uuid_pk`` recreated the table via raw SQL with custom
# index names rather than Django's auto-generated long ones. Django's
# migration *state* still references the long names from ``core/0001_initial``,
# so a plain ``RenameIndex`` issues ``ALTER INDEX core_donor_last_na_f38a81_idx
# RENAME TO …`` and dies on ``UndefinedTable``. Wrap those 5 renames in
# ``SeparateDatabaseAndState`` with idempotent raw SQL that handles whichever
# physical name the index currently has. The 2 untouched donor indexes
# (``client__571817``, ``contact_90bc85``) and all datafiledonor / systemdonor
# indexes still match Django's state, so they keep the plain ``RenameIndex``.

from typing import Any

from django.db import migrations


def _make_rename_donor_index(
    new_name: str, long_old_name: str, short_old_name: str
) -> migrations.SeparateDatabaseAndState:
    """Three-way idempotent rename for the 5 donor indexes recreated by core/0027.

    Args:
        new_name: target index name expected by Django's post-migration state.
        long_old_name: Django auto-generated name in migration state (from core/0001_initial).
        short_old_name: physical name actually present in production (from core/0027 raw SQL).
    """

    def forward(apps: Any, schema_editor: Any) -> None:
        # Tests run on SQLite; only the PostgreSQL deployments need the
        # physical rename. State operations below keep Django's view consistent.
        if schema_editor.connection.vendor != "postgresql":
            return
        with schema_editor.connection.cursor() as cur:
            cur.execute(
                f"""
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = '{new_name}') THEN
                        IF EXISTS (SELECT 1 FROM pg_class WHERE relname = '{long_old_name}') THEN
                            ALTER INDEX "{long_old_name}" RENAME TO "{new_name}";
                        ELSIF EXISTS (SELECT 1 FROM pg_class WHERE relname = '{short_old_name}') THEN
                            ALTER INDEX "{short_old_name}" RENAME TO "{new_name}";
                        END IF;
                    END IF;
                END $$;
                """
            )

    return migrations.SeparateDatabaseAndState(
        database_operations=[
            migrations.RunPython(forward, reverse_code=migrations.RunPython.noop),
        ],
        state_operations=[
            migrations.RenameIndex(
                model_name="donor",
                new_name=new_name,
                old_name=long_old_name,
            ),
        ],
    )


class Migration(migrations.Migration):
    dependencies = [
        ("donors", "0005_add_systemdonor_normalized_phone"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="datafiledonor",
            new_name="donors_data_client__bb21ec_idx",
            old_name="core_datafi_client__9ad37f_idx",
        ),
        migrations.RenameIndex(
            model_name="datafiledonor",
            new_name="donors_data_data_fi_4c19bd_idx",
            old_name="core_datafi_data_fi_c87196_idx",
        ),
        migrations.RenameIndex(
            model_name="datafiledonor",
            new_name="donors_data_last_na_64ae78_idx",
            old_name="core_datafi_last_na_b7331d_idx",
        ),
        migrations.RenameIndex(
            model_name="datafiledonor",
            new_name="donors_data_email_4803a9_idx",
            old_name="core_datafi_email_9b1866_idx",
        ),
        migrations.RenameIndex(
            model_name="datafiledonor",
            new_name="donors_data_postcod_54b597_idx",
            old_name="core_datafi_postcod_cccbc0_idx",
        ),
        migrations.RenameIndex(
            model_name="datafiledonor",
            new_name="donors_data_contact_c61b63_idx",
            old_name="core_datafi_contact_50dd24_idx",
        ),
        migrations.RenameIndex(
            model_name="donor",
            new_name="donors_dono_client__0b17fc_idx",
            old_name="core_donor_client__571817_idx",
        ),
        _make_rename_donor_index(
            new_name="donors_dono_urn_972a7f_idx",
            long_old_name="core_donor_urn_82d02a_idx",
            short_old_name="core_donor_urn_idx",
        ),
        _make_rename_donor_index(
            new_name="donors_dono_last_na_e6a84b_idx",
            long_old_name="core_donor_last_na_f38a81_idx",
            short_old_name="core_donor_name_idx",
        ),
        _make_rename_donor_index(
            new_name="donors_dono_email_17ddb3_idx",
            long_old_name="core_donor_email_e54a71_idx",
            short_old_name="core_donor_email_idx",
        ),
        _make_rename_donor_index(
            new_name="donors_dono_postcod_0d79c7_idx",
            long_old_name="core_donor_postcod_32e474_idx",
            short_old_name="core_donor_postcode_idx",
        ),
        _make_rename_donor_index(
            new_name="donors_dono_verific_78d5fc_idx",
            long_old_name="core_donor_verific_a98710_idx",
            short_old_name="core_donor_verification_idx",
        ),
        migrations.RenameIndex(
            model_name="donor",
            new_name="donors_dono_contact_5f3017_idx",
            old_name="core_donor_contact_90bc85_idx",
        ),
        migrations.RenameIndex(
            model_name="systemdonor",
            new_name="donors_syst_client__d3d59e_idx",
            old_name="core_system_client__f6a3bf_idx",
        ),
        migrations.RenameIndex(
            model_name="systemdonor",
            new_name="donors_syst_client__4c7b2c_idx",
            old_name="core_system_client__82a10f_idx",
        ),
        migrations.RenameIndex(
            model_name="systemdonor",
            new_name="donors_syst_client__a256ef_idx",
            old_name="core_system_client__694633_idx",
        ),
        migrations.RenameIndex(
            model_name="systemdonor",
            new_name="donors_syst_email_141c9a_idx",
            old_name="core_system_email_9b871c_idx",
        ),
        migrations.RenameIndex(
            model_name="systemdonor",
            new_name="donors_syst_phone_7e9adb_idx",
            old_name="core_system_phone_77d3f7_idx",
        ),
        migrations.RenameIndex(
            model_name="systemdonor",
            new_name="donors_syst_postcod_00a0e0_idx",
            old_name="core_system_postcod_2bbc9a_idx",
        ),
        migrations.RenameIndex(
            model_name="systemdonor",
            new_name="donors_syst_contact_34aa48_idx",
            old_name="core_system_contact_1835eb_idx",
        ),
        migrations.RenameIndex(
            model_name="systemdonor",
            new_name="donors_syst_pending_c0bec0_idx",
            old_name="core_system_pending_07c0b0_idx",
        ),
        migrations.AlterModelTable(
            name="datafiledonor",
            table=None,
        ),
        migrations.AlterModelTable(
            name="donor",
            table=None,
        ),
        migrations.AlterModelTable(
            name="donorupload",
            table=None,
        ),
        migrations.AlterModelTable(
            name="segment",
            table=None,
        ),
        migrations.AlterModelTable(
            name="systemdonor",
            table=None,
        ),
    ]
